import type { AccessAction } from './dynamicAccess'

// Explicit operation contract. Keep aligned with backend DynamicViewAccess and domain guards.
export interface DynamicMethodPolicy { view: string; action: AccessAction; organizationArg?: number }
export const dynamicMethodPolicies: Record<string, Record<string, DynamicMethodPolicy>> = {
  pmgmApi: {
    getUserAccountCandidates: { view: 'system', action: 'view' },
    getUserAccounts: { view: 'system', action: 'view' },
    createUserAccount: { view: 'system', action: 'create' },
    getCandidatePortal: { view: 'candidates', action: 'view' },
    getSystemSettings: { view: 'system', action: 'view' },
    createSystemSettingVersion: { view: 'system', action: 'create' },
    getSystemSettingVersions: { view: 'system', action: 'view' },
    getAuditLog: { view: 'access-review', action: 'view' },
    getRegimenInteriorSummary: { view: 'regimen', action: 'view' },
    getOrderRejectionAlerts: { view: 'regimen', action: 'view' },
    setCeremonyInternalAffairsValidation: { view: 'ceremonies', action: 'write' },
    publishCeremonyCandidate: { view: 'candidateprofile', action: 'write' },
    authorizeCeremony: { view: 'ceremonies', action: 'write' },
    registerInitiation: { view: 'ceremonies', action: 'create' },
    recordInitialDeliberation: { view: 'initiationcircuit', action: 'write' },
    uploadInterviewDocument: { view: 'member', action: 'write' },
    recordInterviewPackage: { view: 'initiationcircuit', action: 'write' },
    recordThirdDegreeReview: { view: 'initiationcircuit', action: 'write' },
    recordFinalBallot: { view: 'initiationcircuit', action: 'write' },
    submitInitiationRequest: { view: 'initiationcircuit', action: 'write' },
    getSecretariatAvailability: { view: 'secretariat', action: 'view' },
    getSecretariatDocuments: { view: 'secretariat', action: 'view' },
    getSubmittedTenidas: { view: 'secretariat', action: 'view' },
    reviewSubmittedTenida: { view: 'secretariat', action: 'write' },
    getSecretariatCeremonyQueue: { view: 'secretariat', action: 'view' },
    createSecretariatSpace: { view: 'secretariat', action: 'create' },
    createSecretariatReservation: { view: 'secretariat', action: 'create' },
    issueSecretariatDocument: { view: 'secretariat', action: 'write' },
    issueSecretariatCeremonyAuthorization: { view: 'secretariat', action: 'write' },
    createAdmissionCase: { view: 'admissions', action: 'create' },
    searchAdmissionPeople: { view: 'admissions', action: 'view' },
    createExternalIncorporation: { view: 'admissions', action: 'create' },
    getAdmissionCase: { view: 'admissions', action: 'view' },
    listAdmissionCases: { view: 'admissions', action: 'view', organizationArg: 0 },
    addAdmissionEvidence: { view: 'admissions', action: 'write' },
    reviewAdmissionEvidence: { view: 'admissions', action: 'write' },
    getAdmissionProcedure: { view: 'admissions', action: 'view' },
    recordAdmissionProcedure: { view: 'admissions', action: 'write' },
    createAdmissionCeremony: { view: 'admissions', action: 'create' },
    materializeAdmissionCase: { view: 'admissions', action: 'write' },
    reviewWithdrawalLetterSignature: { view: 'admissions', action: 'write' },
    correctWithdrawalLetterDate: { view: 'admissions', action: 'edit' },
    getCeremonyReviewQueue: { view: 'ceremonies', action: 'view' },
    downloadSubmittedTenidaExtract: { view: 'secretariat', action: 'view' },
  },
  membershipApi: {
    getMembers: { view: 'members', action: 'view', organizationArg: 0 },
    getProfile: { view: 'members', action: 'view' },
    getOwnOffices: { view: 'member', action: 'view' },
    getOwnAttendance: { view: 'member', action: 'view' },
    getOwnHospitalaria: { view: 'member', action: 'view' },
    getSelfProfile: { view: 'member', action: 'view' },
    updateSelfContact: { view: 'member', action: 'edit' },
  },
  lodgeApi: {
    getMemberOptions: { view: 'lodge', action: 'view', organizationArg: 0 },
    getHistoricalMemberIntakes: { view: 'lodge', action: 'view', organizationArg: 0 },
    getCorrespondence: { view: 'lodge', action: 'view', organizationArg: 0 },
    createCorrespondence: { view: 'lodge', action: 'create', organizationArg: 0 },
    updateCorrespondenceStatus: { view: 'lodge', action: 'edit' },
    getSecretariatTasks: { view: 'lodge', action: 'view', organizationArg: 0 },
    createSecretariatTask: { view: 'lodge', action: 'create', organizationArg: 0 },
    updateSecretariatTaskStatus: { view: 'lodge', action: 'edit' },
    getAgendaItems: { view: 'lodge', action: 'view', organizationArg: 0 },
    createAgendaItem: { view: 'lodge', action: 'create', organizationArg: 0 },
    updateAgendaStatus: { view: 'lodge', action: 'edit' },
    createHistoricalMemberIntake: { view: 'lodge', action: 'create', organizationArg: 0 },
    submitHistoricalMemberIntake: { view: 'lodge', action: 'write' },
    downloadHistoricalTemplate: { view: 'lodge', action: 'view', organizationArg: 0 },
    importHistoricalMemberIntakes: { view: 'lodge', action: 'write', organizationArg: 0 },
    getAdministrativeMeetings: { view: 'lodge', action: 'view', organizationArg: 0 },
    createAdministrativeMeeting: { view: 'lodge', action: 'create', organizationArg: 0 },
    markAdministrativeMeetingHeld: { view: 'lodge', action: 'write' },
    getCeremonyAuthorizationOptions: { view: 'lodge', action: 'view', organizationArg: 0 },
    getSecretariatRecords: { view: 'lodge', action: 'view', organizationArg: 0 },
    upsertSecretariatRecord: { view: 'lodge', action: 'write', organizationArg: 0 },
    submitTenidaExtract: { view: 'lodge', action: 'write', organizationArg: 0 },
    getWithdrawals: { view: 'lodge', action: 'view', organizationArg: 0 },
    createWithdrawal: { view: 'lodge', action: 'create' },
    getMeetings: { view: 'lodge', action: 'view', organizationArg: 0 },
    createMeeting: { view: 'lodge', action: 'create', organizationArg: 0 },
    markMeetingHeld: { view: 'lodge', action: 'write' },
    closeMeeting: { view: 'lodge', action: 'write' },
    getAttendance: { view: 'lodge', action: 'view' },
    recordAttendance: { view: 'lodge', action: 'write' },
    getMinutes: { view: 'lodge', action: 'view' },
    createMinute: { view: 'lodge', action: 'create' },
    approveMinute: { view: 'lodge', action: 'write' },
    getAnonymousBallots: { view: 'lodge', action: 'view' },
    recordAnonymousBallot: { view: 'lodge', action: 'write' },
    generateMinuteExtract: { view: 'lodge', action: 'view' },
    getInstructions: { view: 'lodge', action: 'view', organizationArg: 0 },
    getOrderInstructionReport: { view: 'lodge', action: 'view' },
    createInstruction: { view: 'lodge', action: 'create', organizationArg: 0 },
    completeInstruction: { view: 'lodge', action: 'write' },
    recordInstructionAttendance: { view: 'lodge', action: 'write' },
  },
  lodgeCouncilApi: {
    getSessions: { view: 'lodge', action: 'view', organizationArg: 0 },
    createSession: { view: 'lodge', action: 'create', organizationArg: 0 },
    getAttendance: { view: 'lodge', action: 'view' },
    recordAttendance: { view: 'lodge', action: 'write' },
    confirmQuorum: { view: 'lodge', action: 'write' },
    getDecisions: { view: 'lodge', action: 'view' },
    recordDecision: { view: 'lodge', action: 'write' },
    getReviews: { view: 'lodge', action: 'view' },
    recordReview: { view: 'lodge', action: 'write' },
    closeSession: { view: 'lodge', action: 'write' },
  },
  organizationProfileApi: {
  },
  documentApi: {
    getLibrary: { view: 'library', action: 'view' },
    getMyWorkPapers: { view: 'library', action: 'view' },
    getWorkPaperByVersion: { view: 'library', action: 'view' },
    submitWorkPaper: { view: 'library', action: 'create' },
    replaceWorkPaper: { view: 'library', action: 'edit' },
    searchLibrary: { view: 'library', action: 'view' },
    getLibraryFacets: { view: 'library', action: 'view' },
    setLibraryCatalogMetadata: { view: 'documentmanager', action: 'edit' },
    downloadLibraryDocument: { view: 'library', action: 'view' },
    getCollections: { view: 'documentmanager', action: 'view', organizationArg: 0 },
    createCollection: { view: 'documentmanager', action: 'create' },
    getDocuments: { view: 'documentmanager', action: 'view' },
    createDocument: { view: 'documentmanager', action: 'create' },
    getDocument: { view: 'documentmanager', action: 'view' },
    createVersion: { view: 'documentmanager', action: 'create' },
    uploadVersionContent: { view: 'documentmanager', action: 'write' },
    scanVersionContent: { view: 'documentmanager', action: 'write' },
    uploadManagedFile: { view: 'documentmanager', action: 'write' },
    publishDocument: { view: 'documentmanager', action: 'write' },
    unpublishDocument: { view: 'documentmanager', action: 'delete' },
  },
  candidateIntakeApi: {
    getInterviewCases: { view: 'member', action: 'view' },
    getEligibleInterviewers: { view: 'member', action: 'view' },
    getAssignedInterviewers: { view: 'member', action: 'view' },
    assignInterviewers: { view: 'member', action: 'write' },
    retryInterviewerNotifications: { view: 'member', action: 'write' },
    getMyInterviewAssignments: { view: 'member', action: 'view' },
    deliverAssignedInterview: { view: 'member', action: 'write' },
    getPublishedCandidates: { view: 'candidates', action: 'view' },
    getWorkshopQueue: { view: 'candidateprofile', action: 'view' },
    getWorkshopOrganizations: { view: 'candidateprofile', action: 'view' },
    createWorkshopRequest: { view: 'candidateprofile', action: 'create' },
    getOrderRejectionAlerts: { view: 'regimen', action: 'view' },
    getGrandSecretariatQueue: { view: 'candidateprofile', action: 'view' },
    getProfile: { view: 'candidateprofile', action: 'view' },
    saveProfile: { view: 'candidateprofile', action: 'write' },
    attachPhotoVersion: { view: 'candidateprofile', action: 'write' },
    uploadPhoto: { view: 'candidateprofile', action: 'write' },
    getWorkflow: { view: 'initiationcircuit', action: 'view' },
    recordInitialDeliberation: { view: 'initiationcircuit', action: 'write' },
    uploadInterviewDocument: { view: 'initiationcircuit', action: 'write' },
    recordInterviewPackage: { view: 'initiationcircuit', action: 'write' },
    recordThirdDegreeReview: { view: 'initiationcircuit', action: 'write' },
    recordFinalBallot: { view: 'initiationcircuit', action: 'write' },
    submitInitiationRequest: { view: 'initiationcircuit', action: 'write' },
    review: { view: 'candidateprofile', action: 'write' },
    approveAndPublish: { view: 'candidateprofile', action: 'write' },
    getPrivatePhoto: { view: 'candidateprofile', action: 'view' },
    getPublishedPhoto: { view: 'candidates', action: 'view' },
  },
  internalAffairsApi: {
    getMembers: { view: 'regimen', action: 'view' },
    getPendingHistoricalIntakes: { view: 'regimen', action: 'view', organizationArg: 0 },
    reviewHistoricalIntake: { view: 'regimen', action: 'write' },
    getDataQuality: { view: 'regimen', action: 'view' },
  },
  dataQualityCaseApi: {
    listCases: { view: 'regimen', action: 'view' },
    getCase: { view: 'regimen', action: 'view' },
    openCase: { view: 'regimen', action: 'create' },
    claimCase: { view: 'regimen', action: 'write' },
    resolveCase: { view: 'regimen', action: 'write' },
  },
  reportingApi: {
    getExecutiveReport: { view: 'regimen', action: 'view' },
  },
  grandArchiveApi: {
    list: { view: 'grandarchive', action: 'view' },
    candidates: { view: 'grandarchive', action: 'view' },
    register: { view: 'grandarchive', action: 'create' },
    withdraw: { view: 'grandarchive', action: 'delete' },
    download: { view: 'grandarchive', action: 'view' },
  },
  calendarApi: {
    getCalendar: { view: 'calendar', action: 'view' },
    getSpaceConflicts: { view: 'calendar', action: 'view' },
    reconcileSources: { view: 'calendar', action: 'write' },
  },
  notificationApi: {
    getMine: { view: 'notifications', action: 'view' },
    markRead: { view: 'notifications', action: 'write' },
  },
  bootstrapApi: {
    plan: { view: 'system', action: 'view' },
    apply: { view: 'system', action: 'write' },
    catalog: { view: 'system', action: 'view' },
  },
}
