import {describe,it,expect} from 'vitest'
import {PmgmApiClient} from './pmgmApi'

async function setup(){const api=new PmgmApiClient({useMocks:true});const a=(await api.getLodgeTreasuryCharges('org-1',2026,9)).items.find(c=>c.memberId==='member-demo-002')!;const b=(await api.getLodgeTreasuryCharges('org-1',2026,10)).items.find(c=>c.memberId===a.memberId)!;const other=(await api.getLodgeTreasuryCharges('org-1',2026,9)).items.find(c=>c.memberId==='member-demo-003')!;const receipt=await api.recordLodgeMemberReceipt('org-1',{memberId:a.memberId,amount:20000,currency:'CLP',paymentMethod:'transfer',paymentDate:'2026-09-20',idempotencyKey:crypto.randomUUID(),allocations:[{chargeId:a.id,amount:7000}],reference:'EXAMPLE'});return {api,a,b,other,receipt}}
describe('receipt correction and erroneous-record void',()=>{
 it('reallocates without new cash, preserves the source and replays exactly once',async()=>{const {api,b,receipt}=await setup();const before=await api.getLodgeTreasuryReport('org-1','2026-09-01','2026-09-30');const request={kind:'correction' as const,effectiveDate:'2026-09-29',reason:'Mes registrado incorrectamente',idempotencyKey:'fix',allocationId:receipt.allocations[0].id,amount:3000,allocations:[{chargeId:b.id,amount:3000}]};const first=await api.adjustLodgeMemberReceipt(receipt.id,request);expect((await api.adjustLodgeMemberReceipt(receipt.id,request)).id).toBe(first.id);const saved=(await api.getLodgeMemberReceipts('org-1',false)).items[0];expect(saved.allocations[0]).toEqual(receipt.allocations[0]);expect(saved.allocations.map(a=>a.amount)).toEqual([7000,-3000,3000]);expect(saved.unappliedBalance).toBe(13000);expect(saved.adjustments).toHaveLength(1);expect((await api.getLodgeTreasuryReport('org-1','2026-09-01','2026-09-30')).income).toBe(before.income);await expect(api.adjustLodgeMemberReceipt(receipt.id,{...request,reason:'changed'})).rejects.toThrow('clave')})
 it('voids once as a signed income correction, keeps earlier cash reports and blocks reusing credit',async()=>{const {api,b,receipt}=await setup();const earlier=(await api.getLodgeTreasuryReport('org-1','2026-09-01','2026-09-28')).income;const request={kind:'void' as const,effectiveDate:'2026-09-29',reason:'Duplicado sin segundo cobro',idempotencyKey:'void',allocations:[]};const first=await api.adjustLodgeMemberReceipt(receipt.id,request);expect(first.cashAmount).toBe(-20000);expect(first.recordedBySubject).toBe('tesoreria-demo');expect((await api.adjustLodgeMemberReceipt(receipt.id,request)).id).toBe(first.id);const saved=(await api.getLodgeMemberReceipts('org-1',false)).items[0];expect(saved.amount).toBe(receipt.amount);expect(saved.allocations.map(a=>a.amount)).toEqual([7000,-7000]);expect(saved.unappliedBalance).toBe(0);expect((await api.getLodgeTreasuryReport('org-1','2026-09-01','2026-09-28')).income).toBe(earlier);const report=await api.getLodgeTreasuryReport('org-1','2026-09-01','2026-09-30');expect(report.income).toBe(earlier-20000);expect(report.movements.find(m=>m.transactionId===first.id)?.type).toBe('ingreso');await expect(api.allocateLodgeMemberReceipt(receipt.id,[{chargeId:b.id,amount:1000}])).rejects.toThrow('anulado');await expect(api.adjustLodgeMemberReceipt(receipt.id,{...request,idempotencyKey:'again'})).rejects.toThrow('anulado')})
 it('releases a partial allocation to credit and rejects cross-member correction or allocation atomically',async()=>{const {api,other,receipt}=await setup();await expect(api.allocateLodgeMemberReceipt(receipt.id,[{chargeId:other.id,amount:1000}])).rejects.toThrow();const request={kind:'correction' as const,effectiveDate:'2026-09-29',reason:'Liberar exceso imputado',idempotencyKey:'release',allocationId:receipt.allocations[0].id,amount:3000,allocations:[]};await expect(api.adjustLodgeMemberReceipt(receipt.id,{...request,allocations:[{chargeId:other.id,amount:1000}]})).rejects.toThrow('mismo hermano');expect((await api.getLodgeMemberReceipts('org-1',false)).items[0].allocations).toEqual(receipt.allocations);await api.adjustLodgeMemberReceipt(receipt.id,request);expect((await api.getLodgeMemberReceipts('org-1',false)).items[0].unappliedBalance).toBe(16000);await expect(api.adjustLodgeMemberReceipt(receipt.id,{...request,idempotencyKey:'excess',amount:5000})).rejects.toThrow('supera')})
})
