import { afterEach, expect, it, vi } from 'vitest'
import { PmgmApiClient } from './pmgmApi'
afterEach(() => vi.unstubAllGlobals())
it('sends only the access token, with no cookies, caching or redirect following', async () => { const fetch = vi.fn().mockResolvedValue(new Response('{}')); vi.stubGlobal('fetch', fetch); await new PmgmApiClient({ getAccessToken: async () => 'access-token' }).getSystemInfo(); const [url, options] = fetch.mock.calls[0]; expect(url).toBe('/api/system/info'); expect(options.headers.get('Authorization')).toBe('Bearer access-token'); expect(options).toMatchObject({ credentials: 'omit', cache: 'no-store', redirect: 'error' }) })
it('reads effective session capabilities from the API instead of decoding the JWT', async () => { const response = { displayName: 'Hermana Institucional', accessScope: 'order', capabilities: { canApproveTransfers: false, canRunRegimenInteriorReports: true, canManageGrandSecretariat: true, canManageTreasuryRegularity: false, canManageHospitalariaRegularity: false, canEvaluateCeremonies: true, canManagePrivacy: false } }; const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify(response))); vi.stubGlobal('fetch', fetch); expect((await new PmgmApiClient({ getAccessToken: async () => 'token' }).getSessionProfile()).capabilities.canRunRegimenInteriorReports).toBe(true); expect(fetch.mock.calls[0][0]).toBe('/api/session/me') })
it('uses purpose-minimized organization selector endpoint', async () => { const response = { total: 1, items: [{ id: '1', name: 'Taller 1', number: '1', type: 'workshop' }] }; const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify(response))); vi.stubGlobal('fetch', fetch); await new PmgmApiClient({ getAccessToken: async () => 'token' }).getOrganizationOptions(); expect(fetch.mock.calls[0][0]).toBe('/api/institutional/organizations/options') })
it('builds Regimen Interior aggregate query without personal identifiers', async () => { const report = { scope: 'order', organizationId: null, asOf: '2026-09-08', period: { from: '2026-01-01', to: '2026-09-08' }, members: {}, events: {}, financialRegularity: {}, degreeDistribution: {}, pendingTransfers: 0 }; const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify(report))); vi.stubGlobal('fetch', fetch); await new PmgmApiClient({ getAccessToken: async () => 'token' }).getRegimenInteriorSummary({ asOf: '2026-09-08', from: '2026-01-01' }); expect(fetch.mock.calls[0][0]).toBe('/api/regimen-interior/summary?asOf=2026-09-08&from=2026-01-01') })
it('posts Gran Secretaria reservations as JSON with bearer token', async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ id: 'r1', status: 'reserved' }))); vi.stubGlobal('fetch', fetch); await new PmgmApiClient({ getAccessToken: async () => 'token' }).createSecretariatReservation({ spaceId: 's1', organizationId: 'o1', purpose: 'Tenida', startsAtUtc: '2026-09-08T18:00:00Z', endsAtUtc: '2026-09-08T20:00:00Z' }); const [url, options] = fetch.mock.calls[0]; expect(url).toBe('/api/gran-secretaria/reservas'); expect(options.method).toBe('POST'); expect(options.headers.get('Content-Type')).toBe('application/json') })
it('never sends an institutional request without a token', async () => { const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); await expect(new PmgmApiClient().getCandidatePortal()).rejects.toThrow('Debe ingresar'); expect(fetch).not.toHaveBeenCalled() })
it.each([401, 403])('handles HTTP %s without retrying or demo fallback', async status => { const fetch = vi.fn().mockResolvedValue(new Response(null, { status })); const onUnauthorized = vi.fn().mockResolvedValue(undefined); vi.stubGlobal('fetch', fetch); await expect(new PmgmApiClient({ getAccessToken: async () => 'token', onUnauthorized }).getCandidatePortal()).rejects.toThrow(); expect(fetch).toHaveBeenCalledTimes(1); expect(onUnauthorized).toHaveBeenCalledTimes(status === 401 ? 1 : 0) })
it('demo does not request token or network', async () => { const fetch = vi.fn(), token = vi.fn(); vi.stubGlobal('fetch', fetch); const client = new PmgmApiClient({ useMocks: true, getAccessToken: token }); await client.getSystemInfo(); await client.getRegimenInteriorSummary(); await client.getSecretariatAvailability('2026-09-08T18:00:00Z', '2026-09-08T20:00:00Z'); expect(fetch).not.toHaveBeenCalled(); expect(token).not.toHaveBeenCalled() })
