import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { PmgmApiClient } from './pmgmApi'
import { initialTariff, nextTariffPeriod, tariffAt, tariffRate, zoneFromLocation } from './treasuryTariffs'
import { chileCivilDate } from '../admissionDates'
describe('Tarifario por decreto v2',()=>{
 it('mantiene el seed de migración y demo idénticos al contrato inicial',()=>{const backend=readFileSync(new URL('../../../backend/src/PMGM.Api/Modules/Treasury/decree-1759.json',import.meta.url),'utf8');const frontend=readFileSync(new URL('./decree-1759.json',import.meta.url),'utf8');expect(frontend).toBe(backend)})
 it('aplica nuevas versiones hacia adelante y bloquea celdas sin definición',()=>{const future={...structuredClone(initialTariff),id:'new',version:2,effectiveFrom:'2026-11-01',rates:[{feeType:'normal',territory:'santiago' as const,amount:25000,currency:'CLP' as const}]};const catalog=[initialTariff,future];expect(tariffRate(catalog,'normal','santiago','2026-10-31')?.amount).toBe(21000);expect(tariffRate(catalog,'normal','santiago','2026-11-01')?.amount).toBe(25000);expect(tariffRate(catalog,'spouse','santiago','2026-11-01')).toBeNull();expect(tariffAt([initialTariff,{...future,effectiveUntil:'2026-11-30'}],'2026-12-01')).toBeNull();expect(tariffRate([initialTariff],'spouse','peru','2026-10-01')).toBeNull()})
 it('registra sin mutar el decreto anterior y rechaza versiones obsoletas y perfiles locales',async()=>{const api=new PmgmApiClient({useMocks:true});await expect(api.getTariffVersions()).rejects.toThrow('permiso');api.demoAccessSubject='demo:treasury';const initial=await api.getTariffVersions();const payload={...structuredClone(initial.items[0]),number:'QA nuevo',decreeDate:chileCivilDate(),effectiveFrom:nextTariffPeriod(chileCivilDate()),expectedVersion:initial.version};payload.rates[0].amount=25000;const registered=await api.registerTariff(payload);expect(registered.version).toBe(initial.version+1);const current=await api.getTariffVersions();expect(current.items[0].rates[0].amount).toBe(initial.items[0].rates[0].amount);await expect(api.registerTariff(payload)).rejects.toThrow('cambió');expect((await api.getOfficialFeeSchedule(undefined,payload.effectiveFrom)).items[0].amount).toBe(25000);expect((await api.getOfficialFeeSchedule(undefined,'2026-01-01')).items[0].amount).toBe(initial.items[0].rates[0].amount)})
 it('deriva la zona desde Ficha y conserva cesantía como rebaja',()=>{expect(zoneFromLocation('Valparaíso','Chile')).toBe('other_oriente');expect(zoneFromLocation('Lima','Perú')).toBe('peru');expect(zoneFromLocation('', 'Perú')).toBeNull();expect(initialTariff.unemployment.filter(x=>x.territory==='santiago').map(x=>x.discountPercent)).toEqual([100,75,50,25]);expect(initialTariff.unemployment.some(x=>x.territory==='peru')).toBe(false)})
})
