import { useState } from 'react'
import { type PmgmApiClient } from './api/pmgmApi'

type AccessProfile={id:string;name:string;scope:'Orden'|'Taller';protected:boolean;views:string[];actions:string[]}
const views=['Mi ficha','Dashboard','Insinuados','Circuito de iniciación','Miembros','Gestión del Taller','Tesorería','Hospitalaria','Régimen Interior','Gran Secretaría','Biblioteca','Documentos','Gran Archivo','Calendario','Notificaciones','Sistema']
const actions=['Consultar','Crear','Modificar','Eliminar lógico','Cargar archivos','Descargar','Firmar','Aprobar','Rechazar','Publicar','Exportar reportes','Administrar usuarios','Configurar sistema']
const initial:AccessProfile[]=[
 {id:'profile-vm',name:'Venerable Maestro',scope:'Taller',protected:true,views:['Mi ficha','Dashboard','Insinuados','Circuito de iniciación','Miembros','Gestión del Taller','Tesorería','Hospitalaria','Documentos','Calendario','Notificaciones'],actions:['Consultar','Crear','Modificar','Cargar archivos','Descargar','Firmar','Aprobar','Rechazar','Exportar reportes']},
 {id:'profile-secretary',name:'Secretaría del Taller',scope:'Taller',protected:true,views:['Mi ficha','Dashboard','Insinuados','Miembros','Gestión del Taller','Documentos','Calendario','Notificaciones'],actions:['Consultar','Crear','Modificar','Cargar archivos','Descargar','Firmar','Exportar reportes']},
 {id:'profile-system',name:'Administrador del Sistema',scope:'Orden',protected:true,views:['Dashboard','Sistema'],actions:['Consultar','Crear','Modificar','Eliminar lógico','Exportar reportes','Administrar usuarios','Configurar sistema']},
]

export default function AccessProfileDesigner({api,onProfilesChanged}:{api:PmgmApiClient;onProfilesChanged?:(names:string[])=>void}){
 const [profiles,setProfiles]=useState(initial);const [selected,setSelected]=useState(initial[0].id);const [draft,setDraft]=useState(initial[0]);const [message,setMessage]=useState<string|null>(null)
 const choose=(id:string)=>{const profile=profiles.find(item=>item.id===id);if(profile){setSelected(id);setDraft({...profile,views:[...profile.views],actions:[...profile.actions]});setMessage(null)}}
 const toggle=(field:'views'|'actions',value:string)=>setDraft(current=>({...current,[field]:current[field].includes(value)?current[field].filter(item=>item!==value):[...current[field],value]}))
 const save=async()=>{if(!draft.name.trim()||draft.views.length===0){setMessage('El perfil requiere nombre y al menos una vista.');return}const next=profiles.some(item=>item.id===draft.id)?profiles.map(item=>item.id===draft.id?{...draft,name:draft.name.trim()}:item):[{...draft,name:draft.name.trim()},...profiles];await api.createSystemSettingVersion('system.access.profile_definitions',{value:JSON.stringify(next),effectiveFrom:new Date().toISOString().slice(0,10),sourceReference:'Diseñador de perfiles y vistas'});setProfiles(next);onProfilesChanged?.(next.map(item=>item.name));setMessage('Perfil guardado como configuración versionada y auditable.')}
 const duplicate=()=>{const copy={...draft,id:crypto.randomUUID(),name:`Copia de ${draft.name}`,protected:false,views:[...draft.views],actions:[...draft.actions]};setSelected(copy.id);setDraft(copy);setMessage('Copia preparada. Modifique el nombre y guarde el nuevo perfil.')}
 const create=()=>{const item:AccessProfile={id:crypto.randomUUID(),name:'Nuevo perfil',scope:'Taller',protected:false,views:['Mi ficha'],actions:['Consultar']};setSelected(item.id);setDraft(item);setMessage(null)}
 return <section className="system-profile-designer"><header><div><p className="eyebrow">Independencia de configuración</p><h3>Diseñador de perfiles, vistas y acciones</h3></div><button type="button" onClick={create}>Crear perfil</button></header><div className="system-designer-grid"><aside>{profiles.map(profile=><button className={selected===profile.id?'active':''} type="button" key={profile.id} onClick={()=>choose(profile.id)}><strong>{profile.name}</strong><small>{profile.scope}{profile.protected?' · Base protegida':''}</small></button>)}</aside><div className="system-designer-editor"><div className="system-setting-row"><label><span>Nombre del perfil</span><input value={draft.name} onChange={event=>setDraft(current=>({...current,name:event.target.value}))}/></label><label><span>Alcance</span><select value={draft.scope} onChange={event=>setDraft(current=>({...current,scope:event.target.value as AccessProfile['scope']}))}><option>Orden</option><option>Taller</option></select></label></div><fieldset><legend>Vistas visibles</legend><div className="system-check-grid">{views.map(view=><label key={view}><input type="checkbox" checked={draft.views.includes(view)} onChange={()=>toggle('views',view)}/><span>{view}</span></label>)}</div></fieldset><fieldset><legend>Acciones permitidas</legend><div className="system-check-grid">{actions.map(action=><label key={action}><input type="checkbox" checked={draft.actions.includes(action)} onChange={()=>toggle('actions',action)}/><span>{action}</span></label>)}</div></fieldset><div className="system-setting-actions"><button type="button" onClick={()=>void save()}>Guardar versión</button><button className="secondary" type="button" onClick={duplicate}>Duplicar perfil</button></div>{message&&<p className="system-designer-message" role="status">{message}</p>}<p className="system-profile-note">Los perfiles base pueden ajustarse, pero no eliminarse. Los cargos institucionales e históricos permanecen separados de estos permisos técnicos.</p></div></div></section>
}
