import {useMemo,useState} from 'react'

type Review={id:string;user:string;email:string;profile:string;scope:string;risk:'critical'|'attention'|'normal';reason:string;status:'pending'|'certified'|'revoked'}
const initial:Review[]=[
 {id:'rev-1',user:'Administrador QA',email:'admin.qa@ejemplo.cl',profile:'Administrador del Sistema',scope:'Toda la Orden',risk:'critical',reason:'Perfil privilegiado: requiere certificación periódica.',status:'pending'},
 {id:'rev-2',user:'Venerable Demostrativo',email:'vm.taller1@ejemplo.cl',profile:'Venerable Maestro',scope:'Taller Nº 1',risk:'normal',reason:'Cargo vigente y alcance restringido al Taller.',status:'pending'},
 {id:'rev-3',user:'Apoyo Secretaría',email:'apoyo.secretaria@ejemplo.cl',profile:'Secretaría del Taller',scope:'Taller Nº 23',risk:'attention',reason:'Asignación temporal próxima a vencer.',status:'pending'},
]
export function reviewSummary(items:Review[]){return{privileged:items.filter(item=>item.risk==='critical'&&item.status!=='revoked').length,attention:items.filter(item=>item.risk==='attention'&&item.status==='pending').length,pending:items.filter(item=>item.status==='pending').length}}
export default function AccessReviewPanel(){const[items,setItems]=useState(initial);const[filter,setFilter]=useState<'all'|Review['risk']>('all');const[message,setMessage]=useState<string|null>(null);const summary=reviewSummary(items);const visible=useMemo(()=>filter==='all'?items:items.filter(item=>item.risk===filter),[items,filter]);const update=(id:string,status:Review['status'])=>{setItems(current=>current.map(item=>item.id===id?{...item,status}:item));setMessage(status==='certified'?'Acceso certificado y registrado en auditoría.':'Acceso revocado y enviado a sincronización de identidad.')};const exportCsv=()=>{const rows=['Usuario,Correo,Perfil,Alcance,Riesgo,Estado',...items.map(item=>[item.user,item.email,item.profile,item.scope,item.risk,item.status].map(value=>`"${value}"`).join(','))];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='revision-accesos-pmgm.csv';link.click();URL.revokeObjectURL(url);setMessage('Informe CSV de revisión generado.')};return <section className="system-access-review"><header><div><p className="eyebrow">Control periódico</p><h3>Auditoría y certificación de accesos</h3></div><button type="button" onClick={exportCsv}>Exportar revisión</button></header><div className="system-review-summary"><article><strong>{summary.privileged}</strong><span>privilegiados</span></article><article><strong>{summary.attention}</strong><span>requieren atención</span></article><article><strong>{summary.pending}</strong><span>pendientes de certificar</span></article></div><label className="system-review-filter"><span>Filtrar riesgo</span><select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">Todos</option><option value="critical">Crítico</option><option value="attention">Atención</option><option value="normal">Normal</option></select></label><div className="system-review-list">{visible.map(item=><article className={`system-review-row ${item.risk}`} key={item.id}><div><strong>{item.user}</strong><span>{item.email} · {item.profile} · {item.scope}</span><small>{item.reason}</small></div><b>{item.status==='pending'?'Pendiente':item.status==='certified'?'Certificado':'Revocado'}</b>{item.status==='pending'&&<div><button type="button" onClick={()=>update(item.id,'certified')}>Certificar</button><button className="secondary" type="button" onClick={()=>update(item.id,'revoked')}>Revocar</button></div>}</article>)}</div>{message&&<p className="system-designer-message" role="status">{message}</p>}<p className="system-profile-note">Los perfiles privilegiados nunca se consideran aprobados de forma permanente: deben recertificarse según la frecuencia configurada.</p></section>}
