import { useState } from 'react'
import type { PmgmApiClient } from './api/pmgmApi'
import { useDynamicCatalog } from './useDynamicCatalog'
import { assignmentStatus } from './UserAccessAssignments'
export default function AccessReviewPanel({api}:{api:PmgmApiClient}){
 const {catalog,error}=useDynamicCatalog(api);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null)
 const print=async()=>{setBusy(true);try{await api.dynamicAccess.print();window.print();setMessage('Solicitud de impresión autorizada y auditada.')}catch(e){setMessage(e instanceof Error?e.message:'No fue posible imprimir.')}finally{setBusy(false)}}
 const exportCsv=()=>{const cell=(s:string)=>`"${(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')}"`;const rows=[['Sujeto','Perfil','Taller','Desde','Hasta','Estado'],...catalog.assignments.map(a=>[a.subject,a.profileCode,a.organizationId??'Orden',a.effectiveFrom,a.effectiveTo??'',assignmentStatus(a.effectiveFrom,a.effectiveTo??'',!a.isActive)])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(cell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='revision-accesos-pmgm.csv';link.click();URL.revokeObjectURL(url)}
 return <section className="system-access-review"><header><div><p className="eyebrow">Control periódico</p><h3>Auditoría y revisión de accesos</h3></div><div><button disabled={busy||!!error} onClick={exportCsv}>Exportar revisión</button><button className="secondary" disabled={busy||!!error} onClick={()=>void print()}>Imprimir revisión</button></div></header>{error&&<p role="alert">{error}</p>}<p>Versión {catalog.version} · {catalog.assignments.length} asignaciones guardadas</p><div className="system-review-list">{catalog.assignments.map(a=><article key={a.id} className="system-review-row"><div><strong>{a.subject}</strong><span>{catalog.profiles.find(p=>p.code===a.profileCode)?.name} · {a.organizationId??'Orden'}</span><small>{a.effectiveFrom} — {a.effectiveTo??'Sin término'}</small></div><b>{assignmentStatus(a.effectiveFrom,a.effectiveTo??'',!a.isActive)==='active'?'Vigente':'Sin acceso actual'}</b></article>)}</div>{message&&<p role="status">{message}</p>}<p className="system-profile-note">La revisión muestra asignaciones técnicas guardadas. La certificación institucional y las firmas requieren su procedimiento específico.</p></section>
}
