import { useEffect,useMemo,useState } from 'react'
import {type AuditLogEvent,type PmgmApiClient} from './api/pmgmApi'
import './auditableEventLog.css'

export default function AuditableEventLog({api}:{api:PmgmApiClient}){
 const [items,setItems]=useState<AuditLogEvent[]>([]);const [filter,setFilter]=useState('Todos');const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let active=true;api.getAuditLog().then(x=>active&&setItems(x.items)).catch(x=>active&&setError(x instanceof Error?x.message:'No fue posible consultar la bitácora.'));return()=>{active=false}},[api])
 const visible=useMemo(()=>filter==='Todos'?items:items.filter(x=>x.result===filter),[items,filter])
 const exportCsv=()=>{const header=['Fecha y hora','Usuario','IP','Menú','Submenú','Acción','Resultado'];const rows=visible.map(x=>[new Date(x.occurredAtUtc).toLocaleString('es-CL'),x.user,x.ipAddress,x.menu??'',x.submenu??'',x.summary,x.result]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='bitacora-eventos-auditables.csv';a.click();URL.revokeObjectURL(a.href)}
 return <section className="system-event-log"><header><div><p className="eyebrow">Trazabilidad institucional</p><h3>Bitácora de eventos auditables</h3><p>Registro cronológico de accesos y acciones. Los eventos son de solo lectura y no pueden modificarse ni eliminarse desde el sistema.</p></div><span className="system-demo-badge">Inmutable</span></header>{error&&<div className="error-banner">{error}</div>}<div className="system-event-toolbar"><label><span>Resultado</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option value="success">Satisfactorio</option><option value="rejected">No satisfactorio</option><option value="observed">Observado</option></select></label><button onClick={exportCsv}>Exportar CSV</button></div><div className="system-event-table"><table><thead><tr><th>Fecha y hora</th><th>Usuario / IP</th><th>Menú / submenú</th><th>Acción resumida</th><th>Resultado</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td>{new Date(x.occurredAtUtc).toLocaleString('es-CL')}</td><td><strong>{x.user}</strong><small>{x.ipAddress}</small></td><td><strong>{x.menu}</strong><small>{x.submenu}</small></td><td>{x.summary}</td><td><span className={`system-event-result ${x.result}`}>{x.result==='success'?'Satisfactorio':x.result==='rejected'?'No satisfactorio':'Observado'}</span></td></tr>)}</tbody></table></div></section>
}
