import { useEffect, useRef, useState } from 'react'
import { ActionDrawer } from './actionKit'
import type { PmgmApiClient, HospitalariaContributionObligation, HospitalariaContributionRate } from './api/pmgmApi'
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Santiago'}).format(new Date())
const money=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0})
const status={pending:'Pendiente',submitted:'Pago informado',observed:'Observado',reconciled:'Conciliado'}
const msg=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
export function WorkshopContributions({api,organizationId,period,grand,canCreate,canWrite}:{api:PmgmApiClient;organizationId:string;period:string;grand:boolean;canCreate:boolean;canWrite:boolean}) {
 const [items,setItems]=useState<HospitalariaContributionObligation[]|null>(null),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
 const [rates,setRates]=useState<HospitalariaContributionRate[]>([])
 const [amount,setAmount]=useState(6000),[effectiveFrom,setEffectiveFrom]=useState(today())
 const [year,month]=period.split('-').map(Number),generation=useRef(0)
 useEffect(()=>{const current=++generation.current;setItems(null);setError(null);Promise.all([api.getHospitalariaContributions({organizationId:organizationId||undefined,year,month}),grand?api.getHospitalariaContributionRates():Promise.resolve({items:[]})]).then(([r,versions])=>{if(current===generation.current){setItems(r.items);setRates(versions.items)}}).catch(e=>{if(current===generation.current)setError(msg(e))});return()=>{generation.current++}},[api,organizationId,year,month,revision,grand])
 const run=async(fn:()=>Promise<unknown>,text:string)=>{const current=generation.current;setBusy(true);setError(null);setSuccess('');try{await fn();if(current===generation.current){setSuccess(text);setRevision(x=>x+1)}}catch(e){if(current===generation.current)setError(msg(e))}finally{setBusy(false)}}
 return <section className="panel"><p className="eyebrow">Aporte mensual institucional</p><h2>Aporte fijo por Taller</h2><p>Obligación mensual del Taller, separada de las reposiciones de cada hermano. Monto inicial: {money.format(6000)}. El pago y su comprobante se informan por período a Gran Hospitalaria.</p>{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}{grand&&canCreate&&<ActionDrawer label="Configurar aporte mensual" description="Registrar una nueva versión con vigencia."><form className="regularity-form" onSubmit={e=>{e.preventDefault();void run(()=>api.setHospitalariaContributionRate({amount,effectiveFrom}),'Versión de aporte registrada.')}}><label className="regularity-field"><span>Monto mensual por Taller</span><input type="number" min="1" step="1" required value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label className="regularity-field"><span>Vigente desde</span><input type="date" min={today()} required value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label><button className="regularity-primary" disabled={busy}>Registrar versión</button></form></ActionDrawer>}
 {grand&&rates.length>0&&<details><summary>Versiones del aporte mensual</summary><ul>{rates.map(r=><li key={r.id}>{money.format(r.amount)} · Vigente desde {r.effectiveFrom} hasta {r.effectiveUntil??'sin término'}</li>)}</ul></details>}
 {items===null?<p role="status">Consultando aportes del período…</p>:!items.length?<p>No existen aportes generados para este período.</p>:items.map(x=><article className="hospitalaria-submission-card" key={x.id}><div><h3>{x.taller}</h3><p>{String(x.periodMonth).padStart(2,'0')}/{x.periodYear} · {money.format(x.amountDue)} · {status[x.status]}</p><p>Pago: {x.paymentDate??'Sin informar'} · Comprobante: {x.paymentReference??'—'}</p>{x.reviewNotes&&<p>Observación: {x.reviewNotes}</p>}</div>{!grand&&canWrite&&(x.status==='pending'||x.status==='observed')&&<ContributionPayment item={x} busy={busy} onPay={input=>void run(()=>api.payHospitalariaContribution(x.id,input),'Pago informado a Gran Hospitalaria.')}/>} {grand&&canWrite&&x.status==='submitted'&&<ContributionReview busy={busy} onReview={(decision,notes)=>void run(()=>api.reviewHospitalariaContribution(x.id,decision,notes),'Revisión del aporte registrada.')}/>}</article>)}
 </section>
}
function ContributionPayment({item,busy,onPay}:{item:HospitalariaContributionObligation;busy:boolean;onPay:(x:{amount:number;paymentDate:string;reference:string})=>void}) {
 const [paymentDate,setDate]=useState(today()),[reference,setReference]=useState('')
 return <ActionDrawer label="Informar pago de aporte" description="Pago mensual completo del Taller a Gran Hospitalaria."><form className="regularity-form" onSubmit={e=>{e.preventDefault();onPay({amount:item.amountDue,paymentDate,reference})}}><p>Monto: {money.format(item.amountDue)}</p><label className="regularity-field"><span>Fecha real del pago</span><input type="date" required max={today()} value={paymentDate} onChange={e=>setDate(e.target.value)}/></label><label className="regularity-field"><span>Comprobante del aporte</span><input required maxLength={500} value={reference} onChange={e=>setReference(e.target.value)}/></label><button className="regularity-primary" disabled={busy||!reference.trim()}>Informar pago</button></form></ActionDrawer>
}
function ContributionReview({busy,onReview}:{busy:boolean;onReview:(x:'observed'|'reconciled',notes:string)=>void}) {
 const [notes,setNotes]=useState('')
 return <ActionDrawer label="Revisar aporte" description="Verificar la recepción del pago del Taller."><form className="regularity-form" onSubmit={e=>{e.preventDefault();onReview('reconciled',notes)}}><label className="regularity-field"><span>Observación del aporte</span><input maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button type="button" className="regularity-secondary" disabled={busy||!notes.trim()} onClick={()=>onReview('observed',notes)}>Observar aporte</button><button className="regularity-primary" disabled={busy}>Conciliar aporte recibido</button></form></ActionDrawer>
}
export function RegisterHospitalariaDeath({api,organizationId,onRecorded}:{api:PmgmApiClient;organizationId:string;onRecorded:()=>Promise<void>}) {
 const [members,setMembers]=useState<Array<{id:string;displayName:string}>>([]),[memberId,setMember]=useState(''),[deathDate,setDate]=useState(today()),[evidenceReference,setEvidence]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;api.getHospitalariaDeathCandidates(organizationId).then(r=>{if(active)setMembers(r.items)}).catch(e=>{if(active)setError(msg(e))});return()=>{active=false}},[api,organizationId])
 const save=async()=>{setBusy(true);setError('');setSuccess('');try{await api.recordHospitalariaDeath(organizationId,{memberId,deathDate,evidenceReference});setMembers(x=>x.filter(m=>m.id!==memberId));setMember('');setEvidence('');setSuccess('Fallecimiento registrado y reposiciones generadas automáticamente.');await onRecorded()}catch(e){setError(msg(e))}finally{setBusy(false)}}
 return <>{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}<ActionDrawer label="Registrar fallecimiento" description="Registra la defunción y genera las reposiciones con el decreto vigente." confirmMessage="Se registrará el fallecimiento y se generarán las obligaciones de reposición para los hermanos activos."><form className="regularity-form" onSubmit={e=>{e.preventDefault();void save()}}><label className="regularity-field"><span>Hermano del Taller</span><select required value={memberId} onChange={e=>setMember(e.target.value)}><option value="">Seleccionar hermano</option>{members.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label className="regularity-field"><span>Fecha de fallecimiento</span><input type="date" required max={today()} value={deathDate} onChange={e=>setDate(e.target.value)}/></label><label className="regularity-field"><span>Respaldo del fallecimiento</span><input required maxLength={500} value={evidenceReference} onChange={e=>setEvidence(e.target.value)}/></label><button className="regularity-primary" disabled={busy||!memberId||!evidenceReference.trim()}>Registrar y generar reposiciones</button></form></ActionDrawer></>
}
