import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { type LodgeCashSummary, type LodgeFeePlan, type LodgeTreasuryCharge, type LodgeTreasuryExpense, type LodgeTreasuryReport, type LodgeTreasurySummary, type PmgmApiClient, type TreasuryTerritory } from './api/pmgmApi'
import './lodgeTreasury.css'

const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 })
type Section = 'summary'|'collection'|'movements'|'settings'|'reports'

export default function LodgeTreasuryPanel({ api, organizationId, treasuryTerritory, canManage = true, canApproveExpenses = false, section = 'summary' }: { api: PmgmApiClient; organizationId: string; treasuryTerritory?: TreasuryTerritory | null; canManage?: boolean; canApproveExpenses?: boolean; section?: Section }) {
  const now = new Date(); const today = localDate(now)
  const [plans,setPlans]=useState<LodgeFeePlan[]>([]); const [summary,setSummary]=useState<LodgeTreasurySummary|null>(null); const [cash,setCash]=useState<LodgeCashSummary|null>(null)
  const [charges,setCharges]=useState<LodgeTreasuryCharge[]>([]); const [expenses,setExpenses]=useState<LodgeTreasuryExpense[]>([]); const [report,setReport]=useState<LodgeTreasuryReport|null>(null)
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null)
  const [period,setPeriod]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`)
  const [chargeId,setChargeId]=useState(''); const [paymentAmount,setPaymentAmount]=useState(0); const [paymentMethod,setPaymentMethod]=useState<'cash'|'transfer'|'deposit'|'other'>('transfer'); const [paymentDate,setPaymentDate]=useState(today); const [paymentReference,setPaymentReference]=useState('')
  const [expenseCategory,setExpenseCategory]=useState('Servicios'); const [expenseAmount,setExpenseAmount]=useState(0); const [expenseDate,setExpenseDate]=useState(today); const [expenseDescription,setExpenseDescription]=useState(''); const [expenseEvidence,setExpenseEvidence]=useState('')
  const [incomeCategory,setIncomeCategory]=useState('Otros ingresos'); const [incomeAmount,setIncomeAmount]=useState(0); const [incomeDate,setIncomeDate]=useState(today); const [incomeDescription,setIncomeDescription]=useState(''); const [incomeEvidence,setIncomeEvidence]=useState('')
  const [feeType,setFeeType]=useState<LodgeFeePlan['feeType']>('spouse');const [feeMemberAmount,setFeeMemberAmount]=useState(15000);const [feeEffectiveFrom,setFeeEffectiveFrom]=useState(`${now.getFullYear()}-01-01`)
  const [reportFrom,setReportFrom]=useState(`${now.getFullYear()}-01-01`); const [reportTo,setReportTo]=useState(today); const [observedBalance,setObservedBalance]=useState('')
  const [openingBalance,setOpeningBalance]=useState(0);const [openingBalanceDate,setOpeningBalanceDate]=useState(`${now.getFullYear()}-01-01`);const [incomeCategories,setIncomeCategories]=useState('Otros ingresos');const [expenseCategories,setExpenseCategories]=useState('Servicios;Materiales;Arriendo;Traslado')
  const feeGrandAmount=officialFeeAmount(feeType,treasuryTerritory,feeEffectiveFrom)
  const year=Number(period.slice(0,4)); const month=Number(period.slice(5,7)); const from=`${period}-01`; const to=useMemo(()=>`${period}-${String(new Date(Date.UTC(year,month,0)).getUTCDate()).padStart(2,'0')}`,[period,year,month])
  const refresh=useCallback(async()=>{if(!organizationId)return;const requests:Promise<unknown>[]=[api.getLodgeTreasuryExpenses(organizationId,from,to)];if(canManage)requests.push(api.getLodgeFeePlans(organizationId),api.getLodgeTreasurySummary(organizationId,year,month),api.getLodgeTreasuryCharges(organizationId,year,month),api.getLodgeCashSummary(organizationId,today),api.getLodgeTreasuryReport(organizationId,reportFrom,reportTo,observedBalance===''?null:Number(observedBalance)),api.getLodgeTreasuryConfiguration(organizationId));const result=await Promise.all(requests);setExpenses((result[0] as {items:LodgeTreasuryExpense[]}).items);if(canManage){setPlans((result[1] as {items:LodgeFeePlan[]}).items);setSummary(result[2] as LodgeTreasurySummary);setCharges((result[3] as {items:LodgeTreasuryCharge[]}).items);setCash(result[4] as LodgeCashSummary);setReport(result[5] as LodgeTreasuryReport);const config=result[6] as {openingBalance:number;openingBalanceDate:string;incomeCategories:string;expenseCategories:string};setOpeningBalance(config.openingBalance);setOpeningBalanceDate(config.openingBalanceDate);setIncomeCategories(config.incomeCategories);setExpenseCategories(config.expenseCategories)}},[api,organizationId,from,to,year,month,canManage,today,reportFrom,reportTo,observedBalance])
  useEffect(()=>{void refresh().catch(reason=>setError(toMessage(reason)))},[refresh])
  const execute=async(action:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage(null);setError(null);try{await action();await refresh();setMessage(success)}catch(reason){setError(toMessage(reason))}finally{setBusy(false)}}
  const addPayment=(event:FormEvent)=>{event.preventDefault();void execute(()=>api.addLodgeTreasuryPayment(chargeId,{amount:paymentAmount,paymentMethod,paymentDate,reference:paymentReference||null}),'Pago de cuota registrado. Se emitió el comprobante correlativo.').then(()=>{setChargeId('');setPaymentAmount(0);setPaymentReference('')})}
  const addExpense=(event:FormEvent)=>{event.preventDefault();void execute(()=>api.createLodgeTreasuryExpense(organizationId,{category:expenseCategory,amount:expenseAmount,expenseDate,description:expenseDescription,evidenceReference:expenseEvidence||null}),'Egreso registrado y enviado al Venerable Maestro para autorización.').then(()=>{setExpenseAmount(0);setExpenseDescription('');setExpenseEvidence('')})}
  const addIncome=(event:FormEvent)=>{event.preventDefault();void execute(()=>api.createLodgeTreasuryIncome(organizationId,{category:incomeCategory,amount:incomeAmount,incomeDate,description:incomeDescription,evidenceReference:incomeEvidence||null}),'Ingreso registrado en el libro de caja.').then(()=>{setIncomeAmount(0);setIncomeDescription('');setIncomeEvidence('')})}
  const addFeePlan=(event:FormEvent)=>{event.preventDefault();if(feeGrandAmount===null)return;void execute(()=>api.createLodgeFeePlan(organizationId,{feeType,memberAmount:feeMemberAmount,grandTreasuryAmount:feeGrandAmount,effectiveFrom:feeEffectiveFrom}),`${feeLabel(feeType)} configurada desde ${feeEffectiveFrom}.`)}
  const saveConfiguration=(event:FormEvent)=>{event.preventDefault();void execute(()=>api.saveLodgeTreasuryConfiguration(organizationId,{openingBalance,openingBalanceDate,incomeCategories,expenseCategories}),'Configuración contable guardada y auditada.')}
  return <section className="lodge-treasury-panel" id="lodge-treasury">
    <div className="lodge-management-heading"><div><p className="lodge-kicker">Tesorería</p><h2>Operación financiera del Taller</h2><p>Tesorería registra; el Venerable Maestro autoriza los egresos. Gran Tesorería sólo recibe y concilia el Cuadro mensual.</p></div><label><span>Período de cuotas</span><input type="month" value={period} onChange={event=>setPeriod(event.target.value)}/></label></div>
    {message&&<div className="regularity-success" role="status">{message}</div>}{error&&<div className="regularity-error" role="alert">{error}</div>}
    {canManage&&section==='summary'&&<><div className="lodge-treasury-summary cash-summary"><article><small>Saldo neto desde el inicio del registro · {today}</small><strong>{money.format(cash?.cumulativeBalance??0)}</strong></article><article><small>Ingresos del mes</small><strong>{money.format(cash?.monthIncome??0)}</strong></article><article><small>Egresos autorizados del mes</small><strong>{money.format(cash?.monthExpense??0)}</strong></article><article><small>Saldo neto del mes</small><strong>{money.format(cash?.monthBalance??0)}</strong></article><article><small>Egresos pendientes de autorización</small><strong>{cash?.pendingExpenses??0}</strong></article></div><p className="lodge-treasury-note">El saldo acumulado suma movimientos registrados desde el inicio de este módulo; el saldo inicial histórico se muestra como $0 hasta cargarlo en la configuración contable.</p>
      <div className="lodge-fee-grid">{plans.map(plan=><article key={plan.id}><span>{feeLabel(plan.feeType)}</span><strong>{money.format(plan.memberAmount)}</strong><small>Gran Tesorería: {plan.rateAvailable===false?'tarifa/moneda pendiente':money.format(plan.grandTreasuryAmount??0)}</small><em>Disponible para el Taller: {plan.workshopAmount===null?'pendiente':money.format(plan.workshopAmount)}</em></article>)}</div>
      <div className="lodge-treasury-summary"><article><small>Cuotas por cobrar este mes</small><strong>{money.format(summary?.memberExpected??0)}</strong></article><article><small>Recaudado este mes</small><strong>{money.format(summary?.collected??0)}</strong></article><article><small>Saldo por cobrar este mes</small><strong>{money.format(summary?.receivable??0)}</strong></article><article><small>Por pagar a Gran Tesorería</small><strong>{money.format(summary?.grandTreasuryExpected??0)}</strong></article><article><small>Margen proyectado</small><strong>{money.format(summary?.workshopMarginProjected??0)}</strong></article></div>
      <div className="lodge-treasury-action"><div><span className={`treasury-light ${summary?.trafficLight??'no_data'}`}/><p><strong>{summary?.members??0} hermanos cargados en el período</strong><small>{summary?.paid??0} pagados · {summary?.partial??0} parciales · {summary?.overdue??0} pendientes</small></p></div><button className="lodge-blue-button" disabled={busy||!organizationId} onClick={()=>void execute(()=>api.generateLodgeCharges(organizationId,year,month),'Cargos mensuales generados y cartolas actualizadas.')}>{busy?'Procesando…':'Generar cargos del período'}</button></div>
    </>}
    {canManage&&section==='collection'&&<><div className="treasury-collection-summary"><strong>Saldo de cuotas del período: {money.format(charges.reduce((sum,x)=>sum+x.balance,0))}</strong><small>Abre el registro desde la fila del hermano. Los abonos quedan vinculados a su cuota y generan comprobante.</small></div>
      {chargeId&&<div className="treasury-operations-grid single"><form className="regularity-form" onSubmit={addPayment}><p className="lodge-kicker">Cobranza</p><h3>Registrar pago de cuota</h3><label>Hermano y saldo acumulado<select required value={chargeId} onChange={e=>{const selected=charges.find(x=>x.id===e.target.value);setChargeId(e.target.value);setPaymentAmount(selected?.maxPaymentAmount??selected?.balance??0)}}><option value="">Seleccione…</option>{charges.filter(x=>x.balance>0).map(x=><option key={x.id} value={x.id}>{x.memberDisplayName} · adeuda {money.format(x.balance)}</option>)}</select></label><div className="lodge-form-row"><label>Monto del abono<input required min="1" max={charges.find(x=>x.id===chargeId)?.maxPaymentAmount??charges.find(x=>x.id===chargeId)?.balance} type="number" value={paymentAmount||''} onChange={e=>setPaymentAmount(Number(e.target.value))}/></label><label>Medio<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as typeof paymentMethod)}><option value="transfer">Transferencia</option><option value="deposit">Depósito</option><option value="cash">Efectivo</option><option value="other">Otro</option></select></label></div><label>Fecha efectiva<input required type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><label>Referencia<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Transferencia, depósito u observación"/></label><button className="regularity-primary" disabled={busy||!chargeId}>Registrar y emitir comprobante</button><button type="button" className="regularity-secondary" onClick={()=>setChargeId('')}>Cancelar</button></form></div>}
      <div className="table-scroll"><table className="treasury-table"><thead><tr><th>Hermano</th><th>Cuota mensual</th><th>Pagado acumulado al mes</th><th>Saldo adeudado acumulado</th><th>Semáforo</th><th>Acción</th></tr></thead><tbody>{charges.map(x=><tr key={x.memberId}><td>{x.memberDisplayName}</td><td>{money.format(x.monthlyFeeAmount??x.memberAmount)}</td><td>{money.format(x.paidAmount)}</td><td>{money.format(x.balance)}</td><td><span className={`treasury-status-light ${x.balance===0?'green':x.paidAmount>0?'amber':'red'}`}>{x.balance===0?'Al día':x.paidAmount>0?'Abono parcial':'Pendiente'}</span></td><td>{x.balance>0?<button className="regularity-primary" disabled={busy} onClick={()=>{setChargeId(x.id);setPaymentAmount(x.maxPaymentAmount??x.balance)}}>Registrar pago</button>:'—'}</td></tr>)}</tbody></table></div>
    </>}
    {section==='movements'&&<><datalist id="treasury-income-categories">{incomeCategories.split(';').map(x=>x.trim()).filter(Boolean).map(x=><option key={x} value={x}/>)}</datalist><datalist id="treasury-expense-categories">{expenseCategories.split(';').map(x=>x.trim()).filter(Boolean).map(x=><option key={x} value={x}/>)}</datalist><div className="treasury-operations-grid">{canManage&&<><form className="regularity-form" onSubmit={addIncome}><p className="lodge-kicker">Libro de ingresos</p><h3>Registrar otro ingreso</h3><label>Tipo de ingreso<input required list="treasury-income-categories" value={incomeCategory} onChange={e=>setIncomeCategory(e.target.value)}/></label><label>Monto<input required min="1" type="number" value={incomeAmount||''} onChange={e=>setIncomeAmount(Number(e.target.value))}/></label><label>Fecha efectiva<input required type="date" value={incomeDate} onChange={e=>setIncomeDate(e.target.value)}/></label><label>Descripción<textarea required value={incomeDescription} onChange={e=>setIncomeDescription(e.target.value)}/></label><label>Respaldo<input value={incomeEvidence} onChange={e=>setIncomeEvidence(e.target.value)}/></label><button className="regularity-primary" disabled={busy}>Registrar ingreso</button><small>Los pagos de cuotas se contabilizan automáticamente desde Cuotas y Cobranzas.</small></form>
      <form className="regularity-form" onSubmit={addExpense}><p className="lodge-kicker">Libro de egresos</p><h3>Registrar egreso</h3><label>Tipo de egreso<input required list="treasury-expense-categories" value={expenseCategory} onChange={e=>setExpenseCategory(e.target.value)}/></label><label>Monto<input required min="1" type="number" value={expenseAmount||''} onChange={e=>setExpenseAmount(Number(e.target.value))}/></label><label>Fecha efectiva<input required type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)}/></label><label>Descripción<textarea required value={expenseDescription} onChange={e=>setExpenseDescription(e.target.value)}/></label><label>Referencia de respaldo<input value={expenseEvidence} onChange={e=>setExpenseEvidence(e.target.value)} placeholder="Comprobante o documento"/></label><button className="regularity-primary" disabled={busy}>Enviar a autorización</button><small>Todo egreso requiere autorización del Venerable Maestro para afectar la caja.</small></form></>}</div>
      <article className="panel treasury-expenses"><div className="panel-heading"><div><p className="lodge-kicker">Segregación funcional</p><h3>Egresos y autorizaciones</h3></div><span className="count-badge">{expenses.filter(x=>x.approvalStatus==='pending_approval').length} pendientes</span></div><div className="table-scroll"><table className="treasury-table"><thead><tr><th>Fecha</th><th>Categoría / descripción</th><th>Monto</th><th>Respaldo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{x.expenseDate}</td><td><strong>{x.category}</strong><small>{x.description}</small></td><td>{money.format(x.amount)}</td><td>{x.evidenceReference??'Sin referencia'}</td><td>{x.approvalStatus==='approved'?'Autorizado':'Pendiente del Venerable'}</td><td>{canApproveExpenses&&x.approvalStatus==='pending_approval'?<button className="regularity-primary" disabled={busy} onClick={()=>void execute(()=>api.approveLodgeTreasuryExpense(x.id),'Egreso autorizado por el Venerable Maestro.')}>Autorizar</button>:'—'}</td></tr>)}</tbody></table></div></article></>}
    {canManage&&section==='settings'&&<><form className="regularity-form spouse-fee-configuration" onSubmit={saveConfiguration}><p className="lodge-kicker">Caja y clasificación</p><h3>Parámetros contables del Taller</h3><div className="lodge-form-row"><label>Saldo inicial de caja/banco<input required min="0" type="number" value={openingBalance} onChange={e=>setOpeningBalance(Number(e.target.value))}/></label><label>Vigente desde<input required type="date" value={openingBalanceDate} onChange={e=>setOpeningBalanceDate(e.target.value)}/></label></div><label>Tipos de ingreso · separados por punto y coma<textarea required value={incomeCategories} onChange={e=>setIncomeCategories(e.target.value)}/></label><label>Tipos de egreso · separados por punto y coma<textarea required value={expenseCategories} onChange={e=>setExpenseCategories(e.target.value)}/></label><button className="regularity-primary" disabled={busy}>Guardar configuración contable</button></form><div className="lodge-fee-grid">{plans.map(plan=><article key={plan.id}><span>{feeLabel(plan.feeType)}</span><strong>{money.format(plan.memberAmount)}</strong><small>Gran Tesorería: {plan.rateAvailable===false?'tarifa/moneda pendiente':money.format(plan.grandTreasuryAmount??0)}</small><em>Vigente desde {plan.effectiveFrom}</em></article>)}</div><form className="regularity-form spouse-fee-configuration" onSubmit={addFeePlan}><p className="lodge-kicker">Planes con vigencia</p><h3>Configurar cuota mensual local</h3><p>El Taller define su cuota local. El aporte institucional se obtiene del tarifario de Gran Tesorería y no se puede modificar aquí.</p><div className="lodge-form-row"><label>Tipo de cuota<select value={feeType} onChange={e=>{const next=e.target.value as LodgeFeePlan['feeType'];setFeeType(next);setFeeMemberAmount(defaultLocalFeeAmount(next,treasuryTerritory))}}><option value="normal">Normal</option><option value="spouse">Cónyuge</option><option value="student">Estudiante</option><option value="senior">Tercera edad</option><option value="past_active">Past Activo · aporte GT $0</option></select></label><label>Monto cuota local<input required min="0" type="number" value={feeMemberAmount} onChange={e=>setFeeMemberAmount(Number(e.target.value))}/></label><label>Aporte Gran Tesorería<input readOnly aria-label="Aporte decretado a Gran Tesorería" value={feeGrandAmount===null?'Oriente o moneda pendiente':feeGrandAmount}/></label></div><label>Vigente desde<input required type="date" value={feeEffectiveFrom} onChange={e=>setFeeEffectiveFrom(e.target.value)}/></label><p><strong>Oriente:</strong> {territoryLabel(treasuryTerritory)} · <strong>Saldo local:</strong> {feeGrandAmount===null?'—':money.format(feeMemberAmount-feeGrandAmount)}</p><button className="regularity-primary" disabled={busy||feeGrandAmount===null||feeMemberAmount<feeGrandAmount}>Guardar plan de cuota</button></form></>}
    {canManage&&section==='reports'&&<><div className="regularity-form treasury-report-filters"><p className="lodge-kicker">Auditoría y control</p><h3>Cuadratura de caja</h3><div className="lodge-form-row"><label>Desde<input type="date" value={reportFrom} onChange={e=>setReportFrom(e.target.value)}/></label><label>Hasta<input type="date" value={reportTo} onChange={e=>setReportTo(e.target.value)}/></label><label>Saldo efectivo/banco contado<input min="0" type="number" value={observedBalance} onChange={e=>setObservedBalance(e.target.value)} placeholder="Ingresar saldo constatado"/></label><button className="regularity-secondary" onClick={()=>void refresh().catch(reason=>setError(toMessage(reason)))}>Actualizar reporte</button><button className="regularity-primary" disabled={!report} onClick={()=>report&&downloadReport(report)}>Exportar CSV</button></div></div>{report&&<><div className="lodge-treasury-summary"><article><small>Saldo de apertura del período</small><strong>{money.format(report.openingBalance)}</strong></article><article><small>Ingresos (incluye cuotas)</small><strong>{money.format(report.income)}</strong></article><article><small>Egresos autorizados</small><strong>{money.format(report.authorizedExpenses)}</strong></article><article><small>Saldo de cierre calculado</small><strong>{money.format(report.closingBalance)}</strong></article><article><small>Saldo contado</small><strong>{report.observedBalance==null?'Pendiente':money.format(report.observedBalance)}</strong></article><article><small>Diferencia de cuadratura</small><strong>{report.difference==null?'Pendiente':money.format(report.difference)}</strong></article></div><p className="lodge-treasury-note">Los egresos pendientes ({money.format(report.pendingExpenses)}) se muestran para seguimiento, pero no se restan del saldo de caja. El saldo de apertura histórico se considera $0 hasta cargarlo en configuración contable.</p><div className="table-scroll"><table className="treasury-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría / detalle</th><th>Monto</th><th>Estado</th><th>Respaldo</th></tr></thead><tbody>{report.movements.map((x,i)=><tr key={`${x.date}-${i}`}><td>{x.date}</td><td>{x.type==='ingreso'?'Ingreso':'Egreso'}</td><td><strong>{x.category}</strong><small>{x.description}</small></td><td>{money.format(x.amount)}</td><td>{x.status}</td><td>{x.reference??'—'}</td></tr>)}</tbody></table></div></>}</>}
    <p className="lodge-treasury-note">Los documentos oficiales no se generan en el sistema: se registra su descripción y referencia, y el PDF firmado se conserva como respaldo documental.</p>
  </section>
}
function localDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function downloadReport(report:LodgeTreasuryReport){const rows=[['Fecha','Tipo','Categoría','Descripción','Monto','Estado','Referencia'],...report.movements.map(x=>[x.date,x.type,x.category,x.description,String(x.amount),x.status,x.reference??''])];const csv=rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`tesoreria-${report.from}-${report.to}.csv`;link.click();URL.revokeObjectURL(url)}
function feeLabel(value:LodgeFeePlan['feeType']){return value==='student'?'Cuota estudiante':value==='senior'?'Cuota tercera edad':value==='spouse'?'Cuota cónyuge':value==='past_active'?'Cuota Past Activo':'Cuota normal'}
function officialFeeAmount(type:LodgeFeePlan['feeType'],territory:TreasuryTerritory|null|undefined,effectiveFrom:string):number|null{if(effectiveFrom<'2026-01-01')return null;if(type==='past_active')return 0;if(territory==='santiago')return type==='normal'?21000:type==='spouse'?13000:type==='senior'?10000:8000;if(territory==='other_oriente')return type==='normal'?15000:type==='spouse'?10000:type==='senior'?8000:8000;return null}
function defaultLocalFeeAmount(type:LodgeFeePlan['feeType'],territory:TreasuryTerritory|null|undefined){const official=officialFeeAmount(type,territory,'2026-01-01');if(official===null)return 0;return type==='spouse'?15000:official+(type==='past_active'?0:2000)}
function territoryLabel(value:TreasuryTerritory|null|undefined){return value==='santiago'?'Santiago':value==='other_oriente'?'Otros Orientes de Chile':value==='peru'?'Perú · requiere soporte USD':'Sin clasificar'}
function toMessage(reason:unknown){return reason instanceof Error?reason.message:'No fue posible completar la operación de Tesorería.'}
