import { useState, type FormEvent } from 'react'
import type { LodgeMemberReceipt, LodgeTreasuryChargePeriod, PmgmApiClient } from './api/pmgmApi'

type Target = LodgeTreasuryChargePeriod & {memberId:string}
export default function LodgeReceiptAdjustmentsPanel({api,receipts,targets,onSaved,today}:{api:PmgmApiClient;receipts:LodgeMemberReceipt[];targets:Target[];onSaved:()=>Promise<void>;today:string}) {
  const [receiptId,setReceiptId]=useState(''),[kind,setKind]=useState<'correction'|'void'>('correction'),[sourceId,setSourceId]=useState(''),[targetId,setTargetId]=useState(''),[amount,setAmount]=useState(0),[date,setDate]=useState(today),[reason,setReason]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const receipt=receipts.find(r=>r.id===receiptId)
  const remaining=(a:LodgeMemberReceipt['allocations'][number])=>a.amount+(receipt?.allocations??[]).filter(x=>x.reversesAllocationId===a.id).reduce((s,x)=>s+x.amount,0)
  const sources=receipt?.allocations.filter(a=>a.amount>0&&remaining(a)>0)??[]
  const source=sources.find(a=>a.id===sourceId)
  const available=targets.filter(t=>t.memberId===receipt?.memberId&&t.currency===receipt?.currency&&(t.balance>0||t.chargeId===source?.chargeId))
  const change=()=>{setKey(crypto.randomUUID());setMessage('')}
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!receipt)return;setBusy(true);setMessage('');try{await api.adjustLodgeMemberReceipt(receipt.id,{kind,effectiveDate:date,reason,idempotencyKey:key,allocationId:kind==='correction'?sourceId:null,amount:kind==='correction'?amount:null,allocations:kind==='correction'&&targetId?[{chargeId:targetId,amount}]:[]});await onSaved();setMessage('Ajuste guardado. El original y los cierres permanecen en el historial.');setReceiptId('');setReason('');setAmount(0);setKey(crypto.randomUUID())}catch(error){setMessage(error instanceof Error?error.message:'No se pudo guardar el ajuste.')}finally{setBusy(false)}}
  return <article className="panel"><form className="regularity-form treasury-collection-form" onSubmit={submit}>
    <p className="lodge-kicker">Correcciones con historial</p><h3>Corregir imputación o anular registro erróneo</h3>
    <p>La anulación se usa para un recibo duplicado o dinero nunca recibido. La devolución efectiva se tramita por separado. Todo ajuste requiere motivo y fecha en un ejercicio abierto.</p>
    <label>Recibo original<select required value={receiptId} onChange={e=>{change();setReceiptId(e.target.value);setSourceId('');setTargetId('');setAmount(0)}}><option value="">Seleccione un comprobante…</option>{receipts.filter(r=>!r.adjustments?.some(a=>a.kind==='void')).map(r=><option key={r.id} value={r.id}>{r.receiptNumber} · {r.memberDisplayName} · {r.currency} {r.amount}</option>)}</select></label>
    <label>Operación<select value={kind} onChange={e=>{change();setKind(e.target.value as typeof kind)}}><option value="correction">Corregir imputación</option><option value="void">Anular registro erróneo completo</option></select></label>
    {kind==='correction'&&<><label>Imputación original<select required value={sourceId} onChange={e=>{change();setSourceId(e.target.value);setAmount(0)}}><option value="">Seleccione imputación…</option>{sources.map(a=><option key={a.id} value={a.id}>{a.periodMonth}/{a.periodYear} · disponible {remaining(a)}</option>)}</select></label><label>Monto a corregir<input required type="number" min="0.01" step="0.01" max={source?remaining(source):0} value={amount||''} onChange={e=>{change();setAmount(Number(e.target.value))}}/></label><label>Destino<select value={targetId} onChange={e=>{change();setTargetId(e.target.value)}}><option value="">Liberar a saldo a favor</option>{available.map(t=><option key={t.chargeId} value={t.chargeId}>{t.periodMonth}/{t.periodYear} · saldo {t.balance}</option>)}</select></label></>}
    <label>Fecha efectiva del ajuste<input required type="date" value={date} onChange={e=>{change();setDate(e.target.value)}}/></label><label>Motivo<textarea required maxLength={1000} value={reason} onChange={e=>{change();setReason(e.target.value)}}/></label>
    <button className="regularity-primary" disabled={busy||!receipt||!reason.trim()||(kind==='correction'&&(!source||amount<=0))}>{kind==='void'?'Registrar anulación por error':'Guardar corrección'}</button>{message&&<p role="status">{message}</p>}
  </form><div className="treasury-period-history"><h4>Historial de ajustes</h4>{receipts.flatMap(r=>(r.adjustments??[]).map(a=><p key={a.id}><strong>{r.receiptNumber} · {a.kind==='void'?'Anulación de registro':'Corrección de imputación'}</strong> · {a.effectiveDate}<br/>{a.reason}<br/><small>{a.recordedBySubject} · {a.recordedAtUtc}</small></p>))}</div></article>
}
