import { type FormEvent, useEffect, useState } from 'react'
import { type LodgeAgendaItem, type LodgeApiClient, type LodgeCorrespondence, type LodgeMeeting, type LodgeSecretariatTask } from './api/lodgeApi'

type Props={organizationId:string;api:LodgeApiClient;meetings:LodgeMeeting[];canManage:boolean}
const today=()=>new Date().toISOString().slice(0,10)

export default function OperationalSecretariatPanel({organizationId,api,meetings,canManage}:Props){
 const [correspondence,setCorrespondence]=useState<LodgeCorrespondence[]>([]),[tasks,setTasks]=useState<LodgeSecretariatTask[]>([]),[agenda,setAgenda]=useState<LodgeAgendaItem[]>([])
 const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [direction,setDirection]=useState<'received'|'sent'>('received'),[folio,setFolio]=useState(''),[date,setDate]=useState(today()),[subject,setSubject]=useState(''),[counterparty,setCounterparty]=useState(''),[channel,setChannel]=useState<LodgeCorrespondence['channel']>('email'),[reference,setReference]=useState('')
 const [taskTitle,setTaskTitle]=useState(''),[detail,setDetail]=useState(''),[dueDate,setDueDate]=useState(''),[priority,setPriority]=useState<LodgeSecretariatTask['priority']>('normal'),[responsible,setResponsible]=useState('')
 const [meetingId,setMeetingId]=useState(''),[order,setOrder]=useState(1),[agendaTitle,setAgendaTitle]=useState(''),[agendaDetail,setAgendaDetail]=useState('')
 const refresh=async()=>{const [c,t,a]=await Promise.all([api.getCorrespondence(organizationId),api.getSecretariatTasks(organizationId),api.getAgendaItems(organizationId)]);setCorrespondence(c.items);setTasks(t.items);setAgenda(a.items)}
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:String(e)))},[organizationId,api])
 const run=async(fn:()=>Promise<unknown>,ok:string)=>{setBusy(true);setError('');setMessage('');try{await fn();await refresh();setMessage(ok)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const addCorrespondence=(e:FormEvent)=>{e.preventDefault();void run(()=>api.createCorrespondence(organizationId,{direction,folio,correspondenceDate:date,subject,counterparty,channel,reference:reference||null}),'Correspondencia registrada y auditada.').then(()=>{setFolio('');setSubject('');setCounterparty('');setReference('')})}
 const addTask=(e:FormEvent)=>{e.preventDefault();void run(()=>api.createSecretariatTask(organizationId,{title:taskTitle,detail:detail||null,dueDate:dueDate||null,priority,responsible:responsible||null}),'Pendiente registrado.').then(()=>{setTaskTitle('');setDetail('');setDueDate('');setResponsible('')})}
 const addAgenda=(e:FormEvent)=>{e.preventDefault();void run(()=>api.createAgendaItem(organizationId,{meetingId:meetingId||null,order,title:agendaTitle,detail:agendaDetail||null}),'Punto incorporado a la tabla de agenda.').then(()=>{setAgendaTitle('');setAgendaDetail('');setOrder(x=>x+1)})}
 return <section className="operational-secretariat">
  <div className="panel-heading"><div><p className="eyebrow">Operación diaria</p><h3>Correspondencia, pendientes y tabla de agenda</h3></div><span className="count-badge">{correspondence.length+tasks.length+agenda.length} registros</span></div>
  {error&&<div className="error-banner">{error}</div>}{message&&<div className="regularity-success">{message}</div>}
  <div className="operational-secretariat-grid">
   <article className="panel"><h4>Correspondencia</h4>{canManage&&<form className="regularity-form" onSubmit={addCorrespondence}><div className="lodge-form-row"><label>Dirección<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="received">Recibida</option><option value="sent">Enviada</option></select></label><label>Folio<input required value={folio} onChange={e=>setFolio(e.target.value)}/></label></div><label>Fecha<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Asunto<input required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Contraparte<input required value={counterparty} onChange={e=>setCounterparty(e.target.value)}/></label><div className="lodge-form-row"><label>Canal<select value={channel} onChange={e=>setChannel(e.target.value as typeof channel)}><option value="email">Correo</option><option value="letter">Carta</option><option value="hand_delivery">Entrega personal</option><option value="other">Otro</option></select></label><label>Referencia<input value={reference} onChange={e=>setReference(e.target.value)}/></label></div><button className="regularity-primary" disabled={busy}>Registrar</button></form>}<div className="lodge-secretariat-list">{correspondence.map(x=><div key={x.id}><div><strong>{x.folio} · {x.subject}</strong><span>{x.direction==='received'?'Recibida':'Enviada'} · {x.correspondenceDate}</span><small>{x.counterparty} · {x.channel}</small></div>{canManage&&x.status!=='closed'&&<button className="regularity-secondary" onClick={()=>void run(()=>api.updateCorrespondenceStatus(x.id,'closed'),'Correspondencia cerrada.')}>Cerrar</button>}</div>)}</div></article>
   <article className="panel"><h4>Pendientes</h4>{canManage&&<form className="regularity-form" onSubmit={addTask}><label>Título<input required value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/></label><label>Detalle<textarea value={detail} onChange={e=>setDetail(e.target.value)}/></label><div className="lodge-form-row"><label>Vencimiento<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><label>Responsable institucional<input value={responsible} onChange={e=>setResponsible(e.target.value)}/></label><button className="regularity-primary" disabled={busy}>Agregar</button></form>}<div className="lodge-secretariat-list">{tasks.map(x=><div key={x.id}><div><strong>{x.title}</strong><span>{x.priority} · {x.dueDate||'sin vencimiento'} · {x.status}</span><small>{x.responsible||'Sin responsable asignado'}</small></div>{canManage&&x.status!=='completed'&&x.status!=='cancelled'&&<button className="regularity-secondary" onClick={()=>void run(()=>api.updateSecretariatTaskStatus(x.id,'completed'),'Pendiente completado.')}>Completar</button>}</div>)}</div></article>
   <article className="panel operational-agenda"><h4>Tabla de agenda de Tenida</h4>{canManage&&<form className="regularity-form" onSubmit={addAgenda}><label>Tenida<select value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">Sin vincular todavía</option>{meetings.map(x=><option key={x.id} value={x.id}>{x.meetingDate} · {x.title||x.meetingType}</option>)}</select></label><div className="lodge-form-row"><label>Orden<input min="1" type="number" value={order} onChange={e=>setOrder(Number(e.target.value))}/></label><label>Título<input required value={agendaTitle} onChange={e=>setAgendaTitle(e.target.value)}/></label></div><label>Detalle<textarea value={agendaDetail} onChange={e=>setAgendaDetail(e.target.value)}/></label><button className="regularity-primary" disabled={busy}>Agregar punto</button></form>}<div className="lodge-secretariat-list">{agenda.map(x=><div key={x.id}><div><strong>{x.order}. {x.title}</strong><span>{x.status} · {x.meetingId?'Tenida vinculada':'Sin Tenida vinculada'}</span><small>{x.detail||'Sin detalle'}</small></div>{canManage&&x.status==='pending'&&<span><button className="regularity-secondary" onClick={()=>void run(()=>api.updateAgendaStatus(x.id,'covered'),'Punto tratado.')}>Tratado</button><button className="regularity-secondary" onClick={()=>void run(()=>api.updateAgendaStatus(x.id,'deferred'),'Punto postergado.')}>Postergar</button></span>}</div>)}</div></article>
  </div>
 </section>
}
