import { ActionDrawer } from './actionKit'
import { useMemo, useState, type CSSProperties } from 'react'
import AccessProfileDesigner from './AccessProfileDesigner'
import UserAccessAssignments from './UserAccessAssignments'
import UserAccountsPanel from './UserAccountsPanel'
import AccessReviewPanel from './AccessReviewPanel'
import AuditableEventLog from './AuditableEventLog'
import { type PmgmApiClient } from './api/pmgmApi'

export type Area='backup'|'users'|'mail'|'brand'|'audit'
type Backup={id:string;createdAt:string;status:'verified';scope:string}

const baseProfiles=['Administrador del Sistema','Administrador Gran Logia','Venerable Maestro','Secretaría del Taller','Tesorería del Taller','Hospitalaria del Taller','Orador del Taller','Primer Vigilante','Segundo Vigilante','Ex Venerable Maestro','Régimen Interior','Gran Tesorería','Gran Hospitalaria','Gran Secretaría','Gran Archivero','Gran Maestría']

export default function SystemOperationsPanel({api,area:controlledArea}:{api:PmgmApiClient;area?:Area}){
 const [internalArea,setArea]=useState<Area>('backup');const area=controlledArea??internalArea;const [notice,setNotice]=useState<string|null>(null)
 const [profileOptions,setProfileOptions]=useState(baseProfiles)
 const [backups,setBackups]=useState<Backup[]>([{id:'QA-20260914-0200',createdAt:'14-09-2026 02:00',status:'verified',scope:'PostgreSQL · documentos · identidad'}]);const [selected,setSelected]=useState(backups[0].id);const [confirmation,setConfirmation]=useState('')
 const [mail,setMail]=useState({host:'smtp.ejemplo.cl',port:'587',username:'notificaciones@ejemplo.cl',password:'',sender:'Gran Logia Mixta de Chile',security:'STARTTLS'})
 const [brand,setBrand]=useState<{name:string;primary:string;secondary:string;gold:string;accent:string;logo:File|null}>({name:'Gran Logia Mixta de Chile',primary:'#06148E',secondary:'#004AD4',gold:'#F3C609',accent:'#FBAE17',logo:null});const preview=useMemo(()=>brand.logo?URL.createObjectURL(brand.logo):null,[brand.logo])
 const createBackup=()=>{const now=new Date();const item={id:`QA-${now.toISOString().replace(/\D/g,'').slice(0,12)}`,createdAt:now.toLocaleString('es-CL'),status:'verified' as const,scope:'PostgreSQL · documentos · identidad'};setBackups(current=>[item,...current]);setSelected(item.id);setNotice('Respaldo QA generado y verificado. En el instalable se exige además una copia externa protegida.')}
 const restore=()=>{if(confirmation!=='RESTAURAR'){setNotice('Escriba RESTAURAR para confirmar la recuperación controlada.');return}setNotice(`Simulación QA completada desde ${selected}. El instalable ejecuta mantenimiento, restauración y smoke posterior.`);setConfirmation('')}
 const testMail=()=>{if(!mail.host.trim()||!mail.username.includes('@')){setNotice('Complete servidor y cuenta SMTP.');return}setNotice('Conexión SMTP QA validada. La contraseña permanece enmascarada y se almacenará como secreto del servidor.')}
 return <section className="panel system-operations">{!controlledArea&&<header><div><p className="eyebrow">Operación administrativa</p><h2>Consola del sistema</h2></div><span className="system-demo-badge">QA operacional</span></header>}{!controlledArea&&<nav className="system-tabs" aria-label="Áreas del sistema">{([['backup','Backup y restauración'],['users','Usuarios'],['mail','Correo'],['brand','Logos y colores'],['audit','Auditoría de accesos']] as [Area,string][]).map(([key,label])=><button className={area===key?'active':''} key={key} onClick={()=>{setArea(key);setNotice(null)}}>{label}</button>)}</nav>}{notice&&<div className="regularity-success" role="status">{notice}</div>}
 {area==='backup'&&<div className="system-console-grid"><div><h3>Respaldos verificados</h3><button onClick={createBackup}>Generar respaldo ahora</button>{backups.map(item=><label className="system-backup-row" key={item.id}><input type="radio" name="backup" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span><strong>{item.id}</strong><small>{item.createdAt} · {item.scope}</small></span><b>Verificado</b></label>)}</div><div className="action-bar"><ActionDrawer label="Restaurar un respaldo" tone="secondary" title="Restauración controlada" description="Detiene temporalmente los servicios, restaura el respaldo seleccionado y ejecuta pruebas posteriores." keepOpen><div className="system-danger-zone"><p>Respaldo seleccionado: <strong>{selected}</strong></p><label><span>Escriba RESTAURAR</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button disabled={!selected} onClick={restore}>Restaurar respaldo seleccionado</button></div></ActionDrawer></div></div>}
 {area==='users'&&<><UserAccountsPanel api={api}/><div className="action-bar"><ActionDrawer label="Diseñar perfiles de acceso" tone="secondary" title="Diseñador de perfiles, vistas y acciones" description="Crea o ajusta perfiles técnicos y sus permisos. Cada cambio queda auditado." keepOpen><AccessProfileDesigner api={api} onProfilesChanged={names=>setProfileOptions(Array.from(new Set([...baseProfiles,...names])))}/></ActionDrawer></div><UserAccessAssignments api={api} profiles={profileOptions}/></>}
 {area==='mail'&&<div className="system-summary"><dl><div><dt>Servidor</dt><dd>{mail.host}:{mail.port} · {mail.security}</dd></div><div><dt>Cuenta de envío</dt><dd>{mail.username}</dd></div><div><dt>Remitente</dt><dd>{mail.sender}</dd></div></dl><div className="action-bar"><button onClick={testMail}>Probar conexión y envío</button><ActionDrawer label="Editar configuración de correo" tone="secondary" description="Servidor, cuenta, contraseña y remitente." keepOpen><div className="system-console-grid"><div><h3>Servidor y cuenta de correo</h3><label><span>Servidor SMTP</span><input value={mail.host} onChange={event=>setMail(current=>({...current,host:event.target.value}))}/></label><label><span>Puerto</span><input type="number" value={mail.port} onChange={event=>setMail(current=>({...current,port:event.target.value}))}/></label><label><span>Cuenta de envío</span><input type="email" value={mail.username} onChange={event=>setMail(current=>({...current,username:event.target.value}))}/></label></div><div><h3>Seguridad y remitente</h3><label><span>Contraseña / token</span><input type="password" value={mail.password} placeholder="Secreto no visible" onChange={event=>setMail(current=>({...current,password:event.target.value}))}/></label><label><span>Nombre del remitente</span><input value={mail.sender} onChange={event=>setMail(current=>({...current,sender:event.target.value}))}/></label><label><span>Seguridad</span><select value={mail.security} onChange={event=>setMail(current=>({...current,security:event.target.value}))}><option>STARTTLS</option><option>TLS</option></select></label></div></div></ActionDrawer></div></div>}
 {area==='brand'&&<div className="system-summary"><dl><div><dt>Nombre</dt><dd>{brand.name}</dd></div><div><dt>Colores</dt><dd className="system-swatches">{[brand.primary,brand.secondary,brand.gold,brand.accent].map(color=><span key={color} style={{background:color}} title={color}/>)}</dd></div></dl><div className="action-bar"><ActionDrawer label="Editar logos y colores" tone="secondary" description="Nombre, colores institucionales y logotipo." keepOpen><div className="system-console-grid"><div><h3>Identidad institucional</h3><label><span>Nombre</span><input value={brand.name} onChange={event=>setBrand(current=>({...current,name:event.target.value}))}/></label><label><span>Azul institucional</span><input type="color" value={brand.primary} onChange={event=>setBrand(current=>({...current,primary:event.target.value}))}/></label><label><span>Azul complementario</span><input type="color" value={brand.secondary} onChange={event=>setBrand(current=>({...current,secondary:event.target.value}))}/></label><label><span>Dorado</span><input type="color" value={brand.gold} onChange={event=>setBrand(current=>({...current,gold:event.target.value}))}/></label><label><span>Dorado fuerte</span><input type="color" value={brand.accent} onChange={event=>setBrand(current=>({...current,accent:event.target.value}))}/></label><label><span>Logotipo SVG, PNG o JPG</span><input type="file" accept="image/svg+xml,image/png,image/jpeg" onChange={event=>setBrand(current=>({...current,logo:event.target.files?.[0]??null}))}/></label><button onClick={()=>setNotice('Identidad visual QA aplicada a la vista previa. Al guardar se versionará como configuración institucional.')}>Aplicar vista previa</button></div><div className="system-brand-preview" style={{'--preview-primary':brand.primary,'--preview-secondary':brand.secondary,'--preview-gold':brand.gold,'--preview-accent':brand.accent} as CSSProperties}>{preview?<img src={preview} alt="Logotipo temporal"/>:<div className="system-logo-placeholder">GLMC</div>}<h3>{brand.name}</h3><p>Vista previa de encabezados, botones y acentos institucionales.</p><button>Acción institucional</button></div></div></ActionDrawer></div></div>}
 {area==='audit'&&<><AccessReviewPanel api={api}/><AuditableEventLog api={api}/></>}
 </section>
}
