import { useMemo, useState, type CSSProperties } from 'react'

type Area='backup'|'users'|'mail'|'brand'
type QaUser={id:string;name:string;email:string;profile:string;workshop:string}
type Backup={id:string;createdAt:string;status:'verified';scope:string}

const profiles=['Administrador del Sistema','Administrador Gran Logia','Venerable Maestro','Secretaría del Taller','Tesorería del Taller','Hospitalaria del Taller','Orador del Taller','Primer Vigilante','Segundo Vigilante','Ex Venerable Maestro','Régimen Interior','Gran Tesorería','Gran Hospitalaria','Gran Secretaría','Gran Archivero','Gran Maestría']

export default function SystemOperationsPanel(){
 const [area,setArea]=useState<Area>('backup');const [notice,setNotice]=useState<string|null>(null)
 const [backups,setBackups]=useState<Backup[]>([{id:'QA-20260914-0200',createdAt:'14-09-2026 02:00',status:'verified',scope:'PostgreSQL · documentos · identidad'}]);const [selected,setSelected]=useState(backups[0].id);const [confirmation,setConfirmation]=useState('')
 const [users,setUsers]=useState<QaUser[]>([{id:'usr-1',name:'Administrador QA',email:'admin.qa@ejemplo.cl',profile:'Administrador del Sistema',workshop:'Toda la Orden'}]);const [user,setUser]=useState({name:'',email:'',profile:profiles[0],workshop:'Toda la Orden'})
 const [mail,setMail]=useState({host:'smtp.ejemplo.cl',port:'587',username:'notificaciones@ejemplo.cl',password:'',sender:'Gran Logia Mixta de Chile',security:'STARTTLS'})
 const [brand,setBrand]=useState<{name:string;primary:string;secondary:string;logo:File|null}>({name:'Gran Logia Mixta de Chile',primary:'#243b67',secondary:'#d8bd73',logo:null});const preview=useMemo(()=>brand.logo?URL.createObjectURL(brand.logo):null,[brand.logo])
 const createBackup=()=>{const now=new Date();const item={id:`QA-${now.toISOString().replace(/\D/g,'').slice(0,12)}`,createdAt:now.toLocaleString('es-CL'),status:'verified' as const,scope:'PostgreSQL · documentos · identidad'};setBackups(current=>[item,...current]);setSelected(item.id);setNotice('Respaldo QA generado y verificado. En el instalable se exige además una copia externa protegida.')}
 const restore=()=>{if(confirmation!=='RESTAURAR'){setNotice('Escriba RESTAURAR para confirmar la recuperación controlada.');return}setNotice(`Simulación QA completada desde ${selected}. El instalable ejecuta mantenimiento, restauración y smoke posterior.`);setConfirmation('')}
 const createUser=()=>{if(!user.name.trim()||!user.email.includes('@')){setNotice('Nombre y correo válido son obligatorios.');return}setUsers(current=>[{id:crypto.randomUUID(),...user},...current]);setUser(current=>({...current,name:'',email:''}));setNotice('Usuario QA creado y perfil asignado. En el instalable la identidad se crea en Keycloak.')}
 const testMail=()=>{if(!mail.host.trim()||!mail.username.includes('@')){setNotice('Complete servidor y cuenta SMTP.');return}setNotice('Conexión SMTP QA validada. La contraseña permanece enmascarada y se almacenará como secreto del servidor.')}
 return <section className="panel system-operations"><header><div><p className="eyebrow">Operación administrativa</p><h2>Consola del sistema</h2></div><span className="system-demo-badge">QA operacional</span></header><nav className="system-tabs" aria-label="Áreas del sistema">{([['backup','Backup y restauración'],['users','Usuarios'],['mail','Correo'],['brand','Logos y colores']] as [Area,string][]).map(([key,label])=><button className={area===key?'active':''} key={key} onClick={()=>{setArea(key);setNotice(null)}}>{label}</button>)}</nav>{notice&&<div className="regularity-success" role="status">{notice}</div>}
 {area==='backup'&&<div className="system-console-grid"><div><h3>Respaldos verificados</h3><button onClick={createBackup}>Generar respaldo ahora</button>{backups.map(item=><label className="system-backup-row" key={item.id}><input type="radio" name="backup" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span><strong>{item.id}</strong><small>{item.createdAt} · {item.scope}</small></span><b>Verificado</b></label>)}</div><div className="system-danger-zone"><h3>Restauración controlada</h3><p>Detiene temporalmente los servicios, restaura el respaldo seleccionado y ejecuta pruebas posteriores.</p><label><span>Escriba RESTAURAR</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button disabled={!selected} onClick={restore}>Restaurar respaldo seleccionado</button></div></div>}
 {area==='users'&&<div className="system-console-grid"><form onSubmit={event=>{event.preventDefault();createUser()}}><h3>Crear usuario y asignar perfil</h3><label><span>Nombre</span><input value={user.name} onChange={event=>setUser(current=>({...current,name:event.target.value}))}/></label><label><span>Correo</span><input type="email" value={user.email} onChange={event=>setUser(current=>({...current,email:event.target.value}))}/></label><label><span>Perfil</span><select value={user.profile} onChange={event=>setUser(current=>({...current,profile:event.target.value}))}>{profiles.map(profile=><option key={profile}>{profile}</option>)}</select></label><label><span>Alcance / Taller</span><input value={user.workshop} onChange={event=>setUser(current=>({...current,workshop:event.target.value}))}/></label><button>Crear usuario</button></form><div><h3>Usuarios configurados</h3>{users.map(item=><div className="system-user-row" key={item.id}><strong>{item.name}</strong><span>{item.email}</span><small>{item.profile} · {item.workshop}</small></div>)}</div></div>}
 {area==='mail'&&<div className="system-console-grid"><div><h3>Servidor y cuenta de correo</h3><label><span>Servidor SMTP</span><input value={mail.host} onChange={event=>setMail(current=>({...current,host:event.target.value}))}/></label><label><span>Puerto</span><input type="number" value={mail.port} onChange={event=>setMail(current=>({...current,port:event.target.value}))}/></label><label><span>Cuenta de envío</span><input type="email" value={mail.username} onChange={event=>setMail(current=>({...current,username:event.target.value}))}/></label></div><div><h3>Seguridad y remitente</h3><label><span>Contraseña / token</span><input type="password" value={mail.password} placeholder="Secreto no visible" onChange={event=>setMail(current=>({...current,password:event.target.value}))}/></label><label><span>Nombre del remitente</span><input value={mail.sender} onChange={event=>setMail(current=>({...current,sender:event.target.value}))}/></label><label><span>Seguridad</span><select value={mail.security} onChange={event=>setMail(current=>({...current,security:event.target.value}))}><option>STARTTLS</option><option>TLS</option></select></label><button onClick={testMail}>Probar conexión y envío</button></div></div>}
 {area==='brand'&&<div className="system-console-grid"><div><h3>Identidad institucional</h3><label><span>Nombre</span><input value={brand.name} onChange={event=>setBrand(current=>({...current,name:event.target.value}))}/></label><label><span>Color principal</span><input type="color" value={brand.primary} onChange={event=>setBrand(current=>({...current,primary:event.target.value}))}/></label><label><span>Color secundario</span><input type="color" value={brand.secondary} onChange={event=>setBrand(current=>({...current,secondary:event.target.value}))}/></label><label><span>Logotipo SVG, PNG o JPG</span><input type="file" accept="image/svg+xml,image/png,image/jpeg" onChange={event=>setBrand(current=>({...current,logo:event.target.files?.[0]??null}))}/></label><button onClick={()=>setNotice('Identidad visual QA aplicada a la vista previa. Al guardar se versionará como configuración institucional.')}>Aplicar vista previa</button></div><div className="system-brand-preview" style={{'--preview-primary':brand.primary,'--preview-secondary':brand.secondary} as CSSProperties}>{preview?<img src={preview} alt="Logotipo temporal"/>:<div className="system-logo-placeholder">GLMC</div>}<h3>{brand.name}</h3><p>Vista previa de encabezados, botones y acentos institucionales.</p><button>Acción institucional</button></div></div>}
 </section>
}
