import { type FormEvent, useEffect, useState } from 'react'
import type { PmgmApiClient } from './api/pmgmApi'
import { type RegisterTariff, type TariffVersion, type Zone, nextTariffPeriod, tariffAt } from './api/treasuryTariffs'
import { chileCivilDate } from './admissionDates'
import { ActionDrawer } from './actionKit'
import { useTariffAccess } from './useTariffAccess'
import TreasuryTerritoryPage from './TreasuryTerritoryPage'
import './TariffDecreePage.css'
const zones:Zone[]=['santiago','other_oriente','peru']
const zoneLabels:Record<Zone,string>={santiago:'Santiago',other_oriente:'Regiones',peru:'Perú'}
const fees:Record<string,string>={normal:'Ordinaria',spouse:'Cónyuge',senior:'Tercera edad',student:'Estudiante',past_active:'Past Activo'}
const ceremonies:Record<string,string>={initiation:'Iniciación',wage_increase:'Aumento de salario',exaltation:'Exaltación',affiliation:'Afiliación',incorporation:'Incorporación'}
type Cells=Record<string,string>
const key=(zone:Zone,type:string|number)=>`${zone}:${type}`
const money=(amount:number,currency:string)=>new Intl.NumberFormat('es-CL',{style:'currency',currency,maximumFractionDigits:currency==='USD'?2:0}).format(amount)
export default function TariffDecreePage({api}:{api:PmgmApiClient}){
 const [rows,setRows]=useState<TariffVersion[]>([]),[version,setVersion]=useState(0),[step,setStep]=useState(1),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [header,setHeader]=useState({number:'',decreeDate:chileCivilDate(),effectiveFrom:nextTariffPeriod(chileCivilDate()),effectiveUntil:'',sourceReference:'',status:'published' as 'published'|'draft'})
 const [rates,setRates]=useState<Cells>({}),[rights,setRights]=useState<Cells>({}),[currencies,setCurrencies]=useState<Cells>({}),[discounts,setDiscounts]=useState<Cells>({}),[unemployment,setUnemployment]=useState<Cells>({})
 const permission=useTariffAccess(api)
 const canView=permission.access?.actions.includes('view')??false
 const canCreate=permission.access?.actions.includes('create')??false
 const load=async()=>{const result=await api.getTariffVersions();setRows(result.items);setVersion(result.version)}
 useEffect(()=>{
  let active=true
  setOpen(false)
  setMessage('')
  if(!canView){setRows([]);return}
  void api.getTariffVersions().then(result=>{if(active){setRows(result.items);setVersion(result.version);setError('')}}).catch(reason=>{if(active){setRows([]);setError(reason instanceof Error?reason.message:'No se pudieron cargar los decretos.')}})
  return()=>{active=false}
 },[api,canView,permission.access?.version])
 const current=tariffAt(rows,chileCivilDate())
 const begin=(value:boolean)=>{if(value&&!canCreate)return;setOpen(value);if(!value)return;const latest=[...rows].sort((a,b)=>b.version-a.version)[0];setStep(1);setError('');setHeader({number:'',decreeDate:chileCivilDate(),effectiveFrom:nextTariffPeriod(chileCivilDate()),effectiveUntil:'',sourceReference:'',status:'published'});setRates(Object.fromEntries(latest?.rates.map(x=>[key(x.territory,x.feeType),String(x.amount)])??[]));setRights(Object.fromEntries(latest?.ceremonyRights.map(x=>[key(x.territory,x.ceremonyType),String(x.amount)])??[]));setCurrencies(Object.fromEntries(latest?.ceremonyRights.map(x=>[key(x.territory,x.ceremonyType),x.currency])??[]));setDiscounts(Object.fromEntries(latest?.unemployment.map(x=>[key(x.territory,x.quarter),String(x.discountPercent)])??[]));setUnemployment(Object.fromEntries(latest?.unemployment.map(x=>[key(x.territory,x.quarter),String(x.amount)])??[]))}
 const currency=(zone:Zone)=>zone==='peru'?'USD' as const:'CLP' as const
 const payload: RegisterTariff={...header,effectiveUntil:header.effectiveUntil||null,expectedVersion:version,
 rates:zones.flatMap(zone=>Object.keys(fees).filter(type=>type==='past_active'||rates[key(zone,type)]?.trim()).map(type=>({territory:zone,feeType:type,amount:type==='past_active'?0:Number(rates[key(zone,type)]),currency:currency(zone)}))),
 ceremonyRights:zones.flatMap(zone=>Object.keys(ceremonies).filter(type=>rights[key(zone,type)]?.trim()).map(type=>({territory:zone,ceremonyType:type,amount:Number(rights[key(zone,type)]),currency:currencies[key(zone,type)]==='USD'?'USD' as const:'CLP' as const}))),
 unemployment:zones.flatMap(zone=>[1,2,3,4].filter(q=>unemployment[key(zone,q)]?.trim()&&discounts[key(zone,q)]?.trim()).map(q=>({territory:zone,quarter:q,amount:Number(unemployment[key(zone,q)]),discountPercent:Number(discounts[key(zone,q)]),currency:currency(zone)})))}
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!canCreate){setOpen(false);return}if(step<4){setStep(step+1);return}setBusy(true);setError('');try{const row=await api.registerTariff(payload);await load();setMessage(`Decreto N.º ${row.number}, versión ${row.version}, registrado con vigencia desde ${row.effectiveFrom}.`);setOpen(false)}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo registrar el decreto.')}finally{setBusy(false)}}
 const edit=(setter:(value:Cells|((old:Cells)=>Cells))=>void,id:string,value:string)=>setter(old=>({...old,[id]:value}))
 if(!canView)return <section className="panel tariff-decree-panel"><h2>Tarifario por decreto</h2><p role="status">{permission.error??(permission.access?'Su perfil no permite consultar el tarifario.':'Comprobando acceso al tarifario…')}</p></section>
 return <><section className="panel tariff-decree-panel"><div className="section-title"><div><p className="eyebrow">Gran Tesorería</p><h2>Tarifario por decreto</h2><p>Versiones auditadas. Los cargos y pagos históricos conservan sus importes y moneda.</p></div></div>{error&&!open&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="regularity-success" role="status">{message}</div>}
 {!canCreate&&<p role="status">Acceso de consulta. Su perfil no permite registrar nuevos decretos.</p>}
 <div className="action-bar"><ActionDrawer label="Registrar nuevo decreto" description="Decreto y vigencia → cuotas por zona → derechos y cesantía → revisión y confirmación." keepOpen open={open&&canCreate} onOpenChange={begin} disabled={!canCreate||!rows.length||busy}><form className="regularity-form" onSubmit={event=>void submit(event)}><p>Paso {step} de 4</p>{error&&<p role="alert" className="error-banner">{error}</p>}
 {step===1&&<><h3>Decreto y vigencia</h3><label>Número de decreto<input required maxLength={80} value={header.number} onChange={e=>setHeader({...header,number:e.target.value})}/></label><label>Fecha del decreto<input required type="date" value={header.decreeDate} onChange={e=>setHeader({...header,decreeDate:e.target.value})}/></label><div className="lodge-form-row"><label>Vigente desde<input required type="date" min={nextTariffPeriod(chileCivilDate())} value={header.effectiveFrom} onChange={e=>setHeader({...header,effectiveFrom:e.target.value})}/></label><label>Vigente hasta · opcional<input type="date" min={header.effectiveFrom} value={header.effectiveUntil} onChange={e=>setHeader({...header,effectiveUntil:e.target.value})}/></label></div><label>PDF o referencia de respaldo<input required maxLength={1200} value={header.sourceReference} onChange={e=>setHeader({...header,sourceReference:e.target.value})}/></label><label>Estado<select value={header.status} onChange={e=>setHeader({...header,status:e.target.value as 'draft'|'published'})}><option value="published">Publicado · aplica desde su vigencia</option><option value="draft">Borrador · no aplica a cálculos</option></select></label></>}
 {step===2&&<><h3>Cuotas por zona</h3><p>Importes copiados del último decreto para revisión. Una celda vacía significa tarifa no definida; bloquea el cálculo. Past Activo conserva su exención.</p><div className="tariff-zone-grid">{zones.map(zone=><fieldset key={zone}><legend>{zoneLabels[zone]} · {currency(zone)}</legend>{Object.entries(fees).map(([type,label])=><label key={type}>{label}<input aria-label={`${label} ${zoneLabels[zone]}`} type="number" min="0" step={zone==='peru'?'0.01':'1'} readOnly={type==='past_active'} value={type==='past_active'?0:rates[key(zone,type)]??''} onChange={e=>edit(setRates,key(zone,type),e.target.value)}/></label>)}</fieldset>)}</div></>}
 {step===3&&<><h3>Derechos y tabla de cesantía</h3><p>El decreto inicial fija derechos en CLP para todas las zonas. Cesantía expresa porcentaje de rebaja y monto resultante. Las celdas vacías no definen una tarifa.</p><div className="tariff-zone-grid">{zones.map(zone=><fieldset key={zone}><legend>{zoneLabels[zone]}</legend>{Object.entries(ceremonies).map(([type,label])=><div key={type}><label>{label}<input type="number" min="0" step={currencies[key(zone,type)]==='USD'?'0.01':'1'} value={rights[key(zone,type)]??''} onChange={e=>edit(setRights,key(zone,type),e.target.value)}/></label><label>Moneda de {label}<select value={currencies[key(zone,type)]??'CLP'} onChange={e=>edit(setCurrencies,key(zone,type),e.target.value)}><option>CLP</option><option>USD</option></select></label></div>)}<h4>Cesantía · {currency(zone)}</h4>{[1,2,3,4].map(q=><div key={q}><label>Trimestre {q} · rebaja %<input type="number" min="0" max="100" step="0.01" value={discounts[key(zone,q)]??''} onChange={e=>edit(setDiscounts,key(zone,q),e.target.value)}/></label><label>Trimestre {q} · monto<input type="number" min="0" step={zone==='peru'?'0.01':'1'} value={unemployment[key(zone,q)]??''} onChange={e=>edit(setUnemployment,key(zone,q),e.target.value)}/></label></div>)}</fieldset>)}</div></>}
 {step===4&&<><h3>Revisar y confirmar</h3><p>Decreto N.º {header.number} · {header.decreeDate} · {header.status==='draft'?'Borrador':'Publicado'} · vigencia {header.effectiveFrom} — {header.effectiveUntil||'sin término'}</p><p>Respaldo: {header.sourceReference}</p><TariffValues tariff={{...payload,id:'preview',version:version+1}}/><p>Se registra una nueva versión inmutable. Las tarifas no definidas bloquean cálculos. Sin conversiones, indexación ni cambios retroactivos.</p></>}
 <div className="action-bar">{step>1&&<button type="button" className="action-trigger secondary" disabled={busy} onClick={()=>setStep(step-1)}>Volver</button>}<button className="regularity-primary" disabled={busy}>{busy?'Registrando…':step===4?'Confirmar y registrar decreto':'Continuar'}</button></div></form></ActionDrawer></div>
 {current?<article><h3>Vigente · Decreto N.º {current.number}</h3><p>Desde {current.effectiveFrom} · versión {current.version} · {current.sourceReference}</p><TariffValues tariff={current}/></article>:<p>No hay decreto publicado vigente.</p>}
 <h3>Historial de versiones</h3><div className="tariff-history">{[...rows].sort((a,b)=>b.version-a.version).map(row=><details key={row.id}><summary>Decreto N.º {row.number} · v{row.version} · {row.status==='draft'?'Borrador':row.effectiveFrom>chileCivilDate()?'Programado':current?.id===row.id?'Vigente':'Histórico'} · desde {row.effectiveFrom}</summary><p>Fecha del decreto: {row.decreeDate} · hasta {row.effectiveUntil||'sin término'} · {row.sourceReference}</p><TariffValues tariff={row}/></details>)}</div></section><TreasuryTerritoryPage api={api}/></>
}
function TariffValues({tariff}:{tariff:TariffVersion}){return <div className="tariff-zone-grid">{zones.map(zone=><article key={zone}><h4>{zoneLabels[zone]}</h4><dl>{Object.entries(fees).map(([type,label])=>{const rate=tariff.rates.find(x=>x.territory===zone&&x.feeType===type);return <div key={type}><dt>{label}</dt><dd>{rate?money(rate.amount,rate.currency):'No definida'}</dd></div>})}</dl><h4>Derechos ceremoniales</h4><dl>{Object.entries(ceremonies).map(([type,label])=>{const rate=tariff.ceremonyRights.find(x=>x.territory===zone&&x.ceremonyType===type);return <div key={type}><dt>{label}</dt><dd>{rate?money(rate.amount,rate.currency):'No definido'}</dd></div>})}</dl><h4>Cesantía</h4><dl>{[1,2,3,4].map(q=>{const rate=tariff.unemployment.find(x=>x.territory===zone&&x.quarter===q);return <div key={q}><dt>Trimestre {q}</dt><dd>{rate?`${rate.discountPercent}% rebaja · ${money(rate.amount,rate.currency)}`:'No definida'}</dd></div>})}</dl></article>)}</div>}
