import { useMemo,useState } from 'react'
import { type PmgmApiClient } from './api/pmgmApi'

type Assignment={id:string;user:string;email:string;profile:string;scope:string;from:string;until:string;status:'active'|'scheduled'|'revoked'}
const today=()=>new Date().toISOString().slice(0,10)
const profileAccess:Record<string,string[]>={
 'Administrador del Sistema':['Sistema','Administrar usuarios','Configurar sistema','Auditoría'],
 'Venerable Maestro':['Gestión del Taller','Aprobar egresos','Firmar','Ceremonias'],
 'Secretaría del Taller':['Miembros','Actas','Insinuados','Documentos'],
 'Tesorería del Taller':['Cuotas','Ingresos','Egresos','Reportes'],
 'Hospitalaria del Taller':['Aportes','Reposiciones','Egresos','Reportes'],
}

export function assignmentStatus(from:string,until:string,revoked=false):Assignment['status']{if(revoked)return'revoked';const now=today();if(from>now)return'scheduled';if(until&&until<now)return'revoked';return'active'}

export default function UserAccessAssignments({api,profiles}:{api:PmgmApiClient;profiles:string[]}){
 const [items,setItems]=useState<Assignment[]>([{id:'asg-1',user:'Administrador QA',email:'admin.qa@ejemplo.cl',profile:'Administrador del Sistema',scope:'Toda la Orden',from:'2026-01-01',until:'',status:'active'}])
 const [draft,setDraft]=useState({user:'',email:'',profile:profiles[0]??'Administrador del Sistema',scope:'Toda la Orden',from:today(),until:''});const [selectedUser,setSelectedUser]=useState('admin.qa@ejemplo.cl');const [message,setMessage]=useState<string|null>(null)
 const userAssignments=items.filter(item=>item.email===selectedUser&&item.status!=='revoked');const effective=useMemo(()=>Array.from(new Set(userAssignments.flatMap(item=>profileAccess[item.profile]??[item.profile]))),[userAssignments])
 const persist=async(next:Assignment[],source:string)=>{await api.createSystemSettingVersion('system.access.user_assignments',{value:JSON.stringify(next),effectiveFrom:today(),sourceReference:source});setItems(next)}
 const assign=async()=>{if(!draft.user.trim()||!draft.email.includes('@')||!draft.profile){setMessage('Nombre, correo y perfil son obligatorios.');return}if(draft.until&&draft.until<draft.from){setMessage('La fecha de término no puede ser anterior al inicio.');return}const item:Assignment={id:crypto.randomUUID(),...draft,status:assignmentStatus(draft.from,draft.until)};const next=[item,...items];await persist(next,`Asignación de ${draft.profile} a ${draft.email}`);setSelectedUser(draft.email);setMessage(item.status==='scheduled'?'Asignación programada y auditada.':'Perfil asignado y acceso acumulado recalculado.')}
 const revoke=async(id:string)=>{const next=items.map(item=>item.id===id?{...item,status:'revoked' as const}:item);await persist(next,`Revocación de asignación ${id}`);setMessage('Asignación revocada sin eliminar el historial.')}
 const users=Array.from(new Set(items.map(item=>item.email)))
 return <section className="system-assignments"><header><div><p className="eyebrow">Aplicación efectiva</p><h3>Asignaciones de perfiles a usuarios</h3></div><span className="count-badge">{items.filter(item=>item.status==='active').length} activas</span></header><div className="system-assignment-grid"><form onSubmit={event=>{event.preventDefault();void assign()}}><label><span>Nombre del usuario</span><input value={draft.user} onChange={event=>setDraft(current=>({...current,user:event.target.value}))}/></label><label><span>Correo / identidad</span><input type="email" value={draft.email} onChange={event=>setDraft(current=>({...current,email:event.target.value}))}/></label><label><span>Perfil</span><select value={draft.profile} onChange={event=>setDraft(current=>({...current,profile:event.target.value}))}>{profiles.map(profile=><option key={profile}>{profile}</option>)}</select></label><label><span>Alcance</span><input value={draft.scope} onChange={event=>setDraft(current=>({...current,scope:event.target.value}))}/></label><div className="system-setting-row"><label><span>Desde</span><input type="date" value={draft.from} onChange={event=>setDraft(current=>({...current,from:event.target.value}))}/></label><label><span>Hasta (opcional)</span><input type="date" value={draft.until} onChange={event=>setDraft(current=>({...current,until:event.target.value}))}/></label></div><button>Asignar perfil</button></form><div><label><span>Revisar acceso de</span><select value={selectedUser} onChange={event=>setSelectedUser(event.target.value)}>{users.map(user=><option key={user}>{user}</option>)}</select></label><div className="system-effective-access"><strong>Acceso acumulado efectivo</strong><div>{effective.map(permission=><span key={permission}>{permission}</span>)}</div></div>{items.filter(item=>item.email===selectedUser).map(item=><article className={`system-assignment-row ${item.status}`} key={item.id}><div><strong>{item.profile}</strong><span>{item.scope} · {item.from}{item.until?` a ${item.until}`:''}</span></div><b>{item.status==='active'?'Activo':item.status==='scheduled'?'Programado':'Revocado'}</b>{item.status!=='revoked'&&<button className="secondary" type="button" onClick={()=>void revoke(item.id)}>Revocar</button>}</article>)}</div></div>{message&&<p className="system-designer-message" role="status">{message}</p>}<p className="system-profile-note">Un usuario puede acumular varios perfiles. La revocación conserva el antecedente y las asignaciones futuras permanecen programadas hasta su fecha de inicio.</p></section>
}
