services:
  minio:
    image: adobe/s3mock:5.1.0
    command: []
    environment:
      COM_ADOBE_TESTING_S3MOCK_HTTP_PORT: "9000"
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: pmgm-documents

  minio-init:
    image: alpine:3.22
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >-
        until wget -q -O /dev/null http://minio:9000/favicon.ico; do sleep 2; done;
        exit 0
